### ISSUE TITLE
Failed in fastlock.cpp:303:

### ISSUE THREAD

**Issue by fourirakbar** [JohnSully/KeyDB#105]
Hi. Suddenly there was an issue and make our KeyDB down. Our log say that issue is in **fastlock.cpp:303:**. Is there something wrong?

BTW I use KeyDB version 5.0.2, stand alone

> 
Nov 15 11:22:09 keydb-server keydb-server[95835]: keydb-server: fastlock.cpp:303: void fastlock_free(fastlock*): Assertion `(lock->m_ticket.m_active == lock->m_ticket.m_avail) || (lock->m_pidOwner == gettid() && (lock->m_ticket.m_active == lock->m_ticket.m_avail-1))' failed.
Nov 15 11:24:41 keydb-server systemd[1]: keydb.service: Main process exited, code=killed, status=6/ABRT
Nov 15 11:24:41 keydb-server systemd[1]: keydb.service: Failed with result 'signal'.
Nov 15 11:24:44 keydb-server systemd[1]: keydb.service: Service hold-off time over, scheduling restart.
Nov 15 11:24:44 keydb-server systemd[1]: keydb.service: Scheduled restart job, restart counter is at 3.
Nov 15 11:24:44 keydb-server systemd[1]: Stopped keydb service.

**Comment by JohnSully** [comment]
Hi @fourirakbar 

There should be more debugging information in the log.  Can you provide me the debugging information there?  There should be a line that says: === KEYDB BUG REPORT START: Cut & paste starting from here ===

Send everything after that.

**Comment by fourirakbar** [comment]
Hi @JohnSully 

Here 10 lines before the assert failure, I got it from /var/log/syslog

> ov 15 09:04:46 keydb-server snapd[129121]: storehelpers.go:436: cannot refresh: snap has no updates available: "core", "google-cloud-sdk"
Nov 15 09:04:46 keydb-server snapd[129121]: autorefresh.go:397: auto-refresh: all snaps are up-to-date
Nov 15 09:17:01 keydb-server CRON[199193]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 15 09:23:31 keydb-server systemd[1]: Starting Message of the Day...
Nov 15 09:23:33 keydb-server 50-motd-news[199228]:  * Kata Containers are now fully integrated in Charmed Kubernetes 1.16!
Nov 15 09:23:33 keydb-server 50-motd-news[199228]:    Yes, charms take the Krazy out of K8s Kata Kluster Konstruction.
Nov 15 09:23:33 keydb-server 50-motd-news[199228]:      https://ubuntu.com/kubernetes/docs/release-notes
Nov 15 09:23:33 keydb-server systemd[1]: Started Message of the Day.
Nov 15 10:17:01 keydb-server CRON[199563]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Nov 15 11:17:01 keydb-server CRON[199888]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

Also I will try upgrade to latest version keydb (5.1.1)

**Comment by JohnSully** [comment]
Hi @fourirakbar those are systemd logs which aren't the same as KeyDB's log.  I need the log of KeyDB itself.  It looks like you are using docker so the following command should work:
    docker logs keydb-server

Note that I'm guessing at the docker container name from your systemd logs.  You can use docker ps to find it if I guessed wrong.

**Comment by fourirakbar** [comment]
Hi @JohnSully , there isn't any log related to KeyDB. By the way, I'm not running KeyDB using docker, I use standard systemctl. I think I also wrong config in systemctl keydb about logging..

Now I try upgrade my KeyDB version to 5.1.1
Thanks!
