### ISSUE TITLE
Issue building on container

### ISSUE THREAD

**Issue by eladm92** [JohnSully/KeyDB#110]
I'm having an issue building the project on ubuntu 18.04 container 
My docker file: 

`FROM ubuntu:18.04

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -qqy \
        build-essential nasm autotools-dev autoconf libjemalloc-dev libcurl4-openssl-dev libjemalloc-dev tcl tcl-dev uuid-dev \
    && apt-get clean

COPY . /keydb
WORKDIR keydb`

Error from make command inside the container:
`    LINK keydb-server
server.o: In function `initServer()':
/keydb/src/server.cpp:3045: undefined reference to `uuid_generate'
replication.o: In function `processReplconfUuid(client*, redisObject*)':
/keydb/src/replication.cpp:944: undefined reference to `uuid_parse'
/keydb/src/replication.cpp:949: undefined reference to `uuid_unparse'
replication.o: In function `syncWithMaster(aeEventLoop*, int, void*, int)':
/keydb/src/replication.cpp:2005: undefined reference to `uuid_unparse'
/keydb/src/replication.cpp:2020: undefined reference to `uuid_parse'
replication.o: In function `replicaReplayCommand(client*)':
/keydb/src/replication.cpp:3320: undefined reference to `uuid_parse'
replication.o: In function `replicationFeedSlaves(list*, int, redisObject**, int)':
/keydb/src/replication.cpp:326: undefined reference to `uuid_unparse'
collect2: error: ld returned 1 exit status
Makefile:265: recipe for target 'keydb-server' failed
make[1]: *** [keydb-server] Error 1
make[1]: Leaving directory '/keydb/src'
Makefile:9: recipe for target 'install' failed
make: *** [install] Error 2`

Any clue? 
Thanks...

**Comment by eladm92** [comment]
Closing the issue, I found my problem... 

used this: 
`FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt install -y build-essential nasm autotools-dev autoconf libjemalloc-dev tcl tcl-dev uuid-dev libcurl4-openssl-dev

COPY . /keydb
WORKDIR keydb

RUN make`

**Comment by JohnSully** [comment]
Yea, it looks like you were missing the uuid-dev package.  

I don't really use the build container, but I will update it.
