### ISSUE TITLE
QPS started to drop sharply after a while when enable the FLASH storage

### ISSUE THREAD

**Issue by hengku** [JohnSully/KeyDB#113]
I tried a performance test on the FLASH storage and observed the QPS started to drop sharply after a while (almost down to 0 eventually). Here is my testing environment and scenarios: 

* Successfully complied keydb under Ubuntu 18.04 with: 

  make MALLOC=memkind

* All testing machines have 56 cores, 384GB RAM, 2TB Optane SSD, and 10Gbps network 

* One machine running a keydb server with "server-threads 8", "server-thread-affinity true", "maxmemory 1500gb" 

  I also tried 2, 4 threads with, without binding cores

* One machine running memtier-benchmark as the following: 

  memtier_benchmark -s <ip> -p <port> -d 128 -t 50 -c 1 --key-pattern=P:P -n 200000000 --key-minimum=1 --key-maximum=10000000000 --ratio 1:0 --hide-histogram

  I also tried 5, 10 threads with the payload of 1280, 640 bytes

* From the test cases above, I observed that the QPS started to drop sharply after a while. When that happened, the SSD usage sometimes was above 10GB, 20GB, 40GB.

**Comment by JohnSully** [comment]
Hi @hengku 

The current FLASH implementation relies upon the linux kernel's paging behavior to decide what to place in FLASH and what to keep in RAM.  Unfortunately it doesn't always do a good job.  We're working on a rewrite of our flash implementation where we decide internally what to page.  If you'd like to help us by testing out this new behaviour send me an email: john at eqalpha dot com.
