### ISSUE TITLE
KeyDB cluster crashes on Publish

### ISSUE THREAD

**Issue by kevinhatry** [JohnSully/KeyDB#115]
**Describe the bug**
the KeyDB process crashes with a SIGSEV when receiving a PUBLISH command.
It happens ~90% of the time whether there are subscribers or not.

Keydb is setup in a 4 machine cluster as an experiment.

** Log Files **
[bug_report.txt](https://github.com/JohnSully/KeyDB/files/3928069/bug_report.txt)

(I can provide several from different crashes)

**To Reproduce**
I am using github.com/mediocregopher/radix (golang) to connect.
I will try to find the smallest code set possible to reproduce.

Reproduced on 5.0.2 and 5.1.1.

**Comment by kevinhatry** [comment]
Here is a simple sample of Go code that always crashes the server :

```
cluster, err := radix.NewCluster(confini.GetList("redis.server"))
	if err == nil {
		err = cluster.Do(radix.Cmd(nil, "PUBLISH", "test:user:xxx:mess:new-sub", "66"))
		if err != nil {
			fmt.Printf("publish error: %v\n", err)
		} else {
			fmt.Printf("ok\n")
		}
	}
```

It fails with error "EOF" and the chosen server is crashed.
Note : there is no subscriber.

When I add a subscriber prior to publishing the code sometimes passes but not consistently.
Here is the sample code (a little more complicated sorry) :

```
ready := make(chan struct{})
	go func() {
		cluster, err := radix.NewCluster(confini.GetList("redis.server"))
		if err == nil {
			ps, err := radix.PersistentPubSubWithOpts("", "", radix.PersistentPubSubConnFunc(func(string, string) (radix.Conn, error) {
				topo := cluster.Topo()
				node := topo[rand.Intn(len(topo))]
				return radix.Dial("tcp", node.Addr)
			}))
			if err == nil {
				rcv := make(chan radix.PubSubMessage)
				err = ps.Subscribe(rcv, "test:user:xxx:mess:new-sub")
				if err == nil {
					ready <- struct{}{}
					for m := range rcv {
						fmt.Printf("message received from pubsub: %s\n", m)
					}
				}
			}
		}
		close(ready)
	}()

	_, ok := <-ready
	if !ok {
		fmt.Printf("cannot get ready\n")
		return
	}

	cluster, err := radix.NewCluster(confini.GetList("redis.server"))
	if err == nil {
		err = cluster.Do(radix.Cmd(nil, "PUBLISH", "test:user:xxx:mess:new-sub", "66"))
		if err != nil {
			fmt.Printf("publish error: %v\n", err)
		} else {
			fmt.Printf("ok\n")
		}
	}
```

**Comment by JohnSully** [comment]
Hi @kevinhatry I've confirmed this is fixed in unstable, I've also repro'd the issue in the release build for v5.1.1.  I'll be publishing a new build shortly.

**Comment by JohnSully** [comment]
v5.2 is published. If you still have issues let me know.

**Comment by kevinhatry** [comment]
Hi @JohnSully ,

I have tested with v5.2 (and unstable) and I can confirm that the issue is fixed.

Thank you.
