### ISSUE TITLE
CentOS 7 Compiling Error...

### ISSUE THREAD

**Issue by zhangshuao** [JohnSully/KeyDB#118]
Hi, Gays:

Compile KeyDB software in centos 7, such as (KeyDB-5.0.1, KeyDB-5.1.1),it doesn't work.

Reported the following error:

**storage.cpp: In function ‘int forkFile()’:
storage.cpp:125:20: error: ‘FICLONE’ was not declared in this scope
     if (ioctl(fdT, FICLONE, memkind_fd(mkdisk)) == -1)
                    ^~~~~~~
storage.cpp:125:20: note: suggested alternative: ‘FILE’
     if (ioctl(fdT, FICLONE, memkind_fd(mkdisk)) == -1)
                    ^~~~~~~
                    FILE**
make[1]: *** [storage.o] Error 1
make[1]: Leaving directory `/root/KeyDB-5.0.1/src'
make: *** [all] Error 2

How to solve?

Thanks....

**Comment by JohnSully** [comment]
Hi I’ve seen this before. CentOS 7 uses an old kernel (3.10). This IOCTL first appeared in 4.5. You need to either upgrade your kernel or build without memkind. 

The FLASH feature requires this IOCTL to work.

**Comment by zhangshuao** [comment]
yeah. but I think it's a bad design. It's too helpless to limit. Generally, the operating system won't upgrade the kernel. The cost of upgrading the kernel is too high.Are you planning to be compatible with CentOS 7 kernel 3.1.10?

**Comment by JohnSully** [comment]
There are no plans to make this feature compatible with older kernels.  There is simply too much work involved and this will resolve itself over time as CentOS gets upgraded.

We are working on a new implementation of FLASH support with higher performance which is coming out in our KeyDB Pro version.  This version will work on older kernels as its a completely different design.

**Comment by vvhungy** [comment]
@zhangshuao can you try to upgrade the kernel to 5.x with elrepo (http://elrepo.org/tiki/tiki-index.php).
