### ISSUE TITLE
Sym linking redis-cli to keydb-cli in docker image

### ISSUE THREAD

**Issue by oruchreis** [JohnSully/KeyDB#123]
Hi, 
When we want to use redis oriented tools/utilities with keydb, we are facing difficulties with lack of redis-cli. Because these tools use redis-cli instead of keydb-cli. 

For example, I want to use keydb in k8s environments with redis-operator [here](https://github.com/spotahome/redis-operator/).

Could you create a symbolic link named "redis-cli" that linked to keydb-cli in the docker image?

**Comment by benschermel** [comment]
A new docker image is available (5.2.0) with symlinks for redis-cli
