### ISSUE TITLE
Documentation fix:

### ISSUE THREAD

**Issue by sigio** [JohnSully/KeyDB#127]
I couldn't find the documentation in this github repo, or a repo that had the documentation, so please redirect me there if it's online somewhere:

in https://docs.keydb.dev/docs/first-test/ ... I think all occurances of redis have been replaced with keydb... but this causes sentences such as: 

If you have never used KeyDB or KeyDB before but want to play around with some commands, install KeyDB then run the server.

Which are clearly wrong

**Comment by benschermel** [comment]
Thanks, I updated the lines you pointed out.  We do plan on reviewing in greater detail, and this  repo will be growing substantially in the coming months. I have made an official repo for KeyDB-docs where you can see and edit the markdown documents used on the website. Feedback and pull requests are welcome and appreciated
https://github.com/benschermel/KeyDB-docs
