### ISSUE TITLE
i found a bug, i use LPush to push 17786 records, but keydb is 88868 records, i have two server with active replication, and i use haproxy.

### ISSUE THREAD

**Issue by hezhiqiang** [JohnSully/KeyDB#129]
mysql store procedure code is:

BEGIN
	DECLARE done INT DEFAULT FALSE;
	DECLARE v_id INT;
	DECLARE v_ret INT;
	DECLARE cur CURSOR FOR SELECT u.user_id FROM kid_users u WHERE u.latest_login_time>=DATE(DATE_ADD(NOW(),INTERVAL -1 DAY)) AND EXISTS(SELECT * FROM kid_child_info WHERE user_id=u.user_id AND gender IN(0,1)) ORDER BY u.latest_login_time DESC;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

	OPEN cur;
	read_loop: LOOP
		FETCH cur INTO v_id;
		IF done THEN
			LEAVE read_loop;
		END IF;

		SET v_ret=redis_command_v2('LPUSH', 'calcReadingRecommendForYou', CONCAT(v_id));
	END LOOP;
	CLOSE cur;
END

**Comment by JohnSully** [comment]
To help narrow this down I have a few questions:

1) Do you have any other clients operating on this list at the same time?  
2) Are you sending writes to both servers simultaneously?  
3) Are you using multimaster?

**Comment by hezhiqiang** [comment]
i changed the procedure to save to a new list, same this problem, 20307 records but list has 113694 records.

1.only one client
2.only one server to send
3.i use active-active

**Comment by hezhiqiang** [comment]
i test in redis, there is the same problem(when i lpush 2000 records, redis is 2001 records):

BEGIN
DECLARE v_index INT DEFAULT 1;
DECLARE v_ret INT;

WHILE v_index<=2000 DO
	SET v_ret=redis_command_v2('LPUSH', 'testKeyDB2', CONCAT(v_index));
	SET v_index=v_index+1;
END WHILE;
END

**Comment by hezhiqiang** [comment]
in java is the same problem(the list value is 2000 to 1 and last is 1000, there is am extra 1000), java code is:

public class XhsTestApplication {
public static void main(String[] args) {
JedisPoolConfig config = new JedisPoolConfig();
config.setMaxTotal(1000);
config.setMaxIdle(50);

	JedisPool jedisPool = new JedisPool(config, "192.168.6.67", 6379, 30000, "xxx");
	
	Jedis jedis = jedisPool.getResource();
	try {
		int i = 1;
		while (i<=2000) {
			jedis.lpush("testKeyDB2", i+"");
			i++;
		}
	} finally {
		jedis.close();
		jedisPool.close();
	}
}
}

**Comment by hezhiqiang** [comment]
it is RedisStudio client bug, i close this issure.

**Comment by JohnSully** [comment]
Thanks for the follwup!

Bug reports help make KeyDB better so I really appreciate you spending the time to report this.
