### ISSUE TITLE
KeyDB vs Redis - YCSB benchmarks

### ISSUE THREAD

**Issue by scriptnull** [JohnSully/KeyDB#138]
Hi, I recently performed a head to head comparison of KeyDB vs Redis with the help of https://github.com/brianfrankcooper/YCSB/ 

The key observation is as follows and would like to know if I am missing something in KeyDB's  configuration that is making it under perform.

"Redis in its default configuration is able to handle 15 million operations* from 20 clients with the guarantee that each request is responded back under 60 seconds. KeyDB on the other hand could only satisfy this guarantee up to ~1 million operations from 20 clients"

*all operations were SET commands

Could the reason for this be, "the thread pool gets exhausted doing data operation and sending back data gets blocked on it" ?

Please excuse me for making the above statement as I have no knowledge on internals of KeyDB. But I am interested in learning more about it and excited if we could make it scale to 15 million ops from 1 million ops. 

#### Redis Configuration
Redis ran in default configuration with `protected mode: no`.

#### KeyDB Configuration
Configuration file of Keydb looks like

```
scratch-file-path /mnt/disks/localssd/storage

maxmemory 10gb

maxmemory-policy allkeys-lru

protected-mode no

server-threads 4
```

I was altering the server-threads ( 1, 2, 3, 4, 8 ) and server-affinity (true/false) throughout the benchmarking process in the quest for better performance.

## Server
Both redis and KeyDB were installed on Google Cloud VM of type n1-standard-8 (8 vCPUs, 30 GB memory)

KeyDB had a local SSD mounted which is being used in the configuration.

--- 

My key queries/concerns from this benchmark are

1. How do we achieve more ops with the guarantee that the response to clients is sent under a reasonable time (atleast 60 seconds) when the server is under load?
2. How useful is the `server-affinity` option? How do we decide when to use it and when not to use it?

Please feel free to comment out if you need any other information.

**Comment by JohnSully** [comment]
The primary reason you are under-performing is you are using "scratch-file-path".  This was our first attempt at FLASH and relied on the kernel's paging infrastructure to make decisions on what to keep in RAM.  Unfortunately the kernel is just not able to make good decisions here.

If you'd like to use FLASH KeyDB Pro has newer implementation based upon RocksDB which has much better performance.  If you remove the "scratch-file-path" config you should see KeyDB outperform.

"server-affinity" tends to help after 2-3 threads.  It tends to negatively affect performance with 2 or fewer threads. The advice here is if you are >2 threads to enable this option and under to leave it disabled.  It is also recommended to disable this if your KeyDB server will run other CPU intensive applications.   Generally speaking you'll get great performance even with this option disabled so its more of a way to maximize your results.

**Comment by JohnSully** [comment]
I'll close for now, but let me know if this doesn't resolve your issue and I will reopen.
