### ISSUE TITLE
brew install keydb

### ISSUE THREAD

**Issue by ankane** [JohnSully/KeyDB#139]
Hi, thanks for this project! Just wanted to let you know that Mac users can now install KeyDB (and its client) with:

```sh
brew install keydb
```

No compiling required! https://github.com/Homebrew/homebrew-core/pull/49417

**Comment by JohnSully** [comment]
Thanks! I really appreciate it.  

Reminds me I need to get my mac CI pipeline finished :)

**Comment by ankane** [comment]
Np. fwiw, GitHub actions works pretty well for Mac CI.

**Comment by ShivamJoker** [comment]
Shouldn't this be mentioned in Readme or somewhere on the website ?
