### ISSUE TITLE
Raspberry Pi 4 - compilation error

### ISSUE THREAD

**Issue by Talkabout** [JohnSully/KeyDB#141]
**Describe the bug**
When trying to compile KeyDB (RELEASE_5 and unstable) I am facing the following error:

```
/tmp/cc8z9Ig1.s: Assembler messages:
/tmp/cc8z9Ig1.s:2877: Error: selected processor does not support `yield' in ARM mode
make[1]: *** [Makefile:308: fastlock.o] Fehler 1
make[1]: Verzeichnis „/home/xxx/KeyDB/src“ wird verlassen
make: *** [Makefile:6: all] Fehler 2
```

**To Reproduce**
Try to compile recent KeyDB source on Raspberry Pi 4

**Comment by JohnSully** [comment]
As a quick workaround you can comment out         __asm__ __volatile__ ("yield"); in src/fastlock.cpp

Yield is only to make the lock more efficient, but the lock will work fine if it it is not supported.  I will work on a patch to detect this features availability.

**Comment by Talkabout** [comment]
Hi @JohnSully ,

thanks for the quick answer!

Your suggestion works, but there was one more issue to solve. After the change in "fastlock.cpp" the compilation process was giving me this:

```
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/8/bits/atomic_base.h:336: undefined reference to `__atomic_fetch_or_8'
/usr/bin/ld: t_stream.o: in function `xreadCommand(client*)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: tracking.o: in function `disableTracking(client*)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/8/bits/atomic_base.h:328: undefined reference to `__atomic_fetch_and_8'
/usr/bin/ld: tracking.o: in function `enableTracking(client*, unsigned long long)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/8/bits/atomic_base.h:336: undefined reference to `__atomic_fetch_or_8'
/usr/bin/ld: /usr/include/c++/8/bits/atomic_base.h:328: undefined reference to `__atomic_fetch_and_8'
/usr/bin/ld: tracking.o: in function `trackingInvalidateKey(redisObject*)':
/usr/include/c++/8/bits/atomic_base.h:396: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:272: keydb-server] Fehler 1
make[1]: Verzeichnis „/home/xxx/KeyDB/src“ wird verlassen
make: *** [Makefile:6: all] Fehler 2
```

I was able to compile by executing the following "make"-command:

`make LDFLAGS='-latomic'`

Hope that helps other people facing similar issues. I will now test keydb for my use cases.

Thanks again!

Bye

**Comment by Talkabout** [comment]
Hi @JohnSully ,

I have compiled KeyDB with the steps above on 2 different machines and activated active replication. Currently everything seems to work as expected.

Thanks again for your quick help!

Bye

**Comment by JohnSully** [comment]
Thanks.  We've been testing ARM on AWS instances, but it looks like we'll have to add Raspberry Pi's to the mix.

**Comment by Talkabout** [comment]
Yes, seems to be a good idea if you want to support Raspberry PIs also :)

Side question: the repository for Debian packages does not work on Raspbian Buster because it seems to be targeting Ubuntu. Is this a known issue or only something I am facing?

Bye

**Comment by JohnSully** [comment]
Change aaca32a modifies the code to only use yield on __aarch64__.  There are some 32-bit arm CPUs that support yield but unless its the rPi I don't think it matters much.
