### ISSUE TITLE
Centos RPM

### ISSUE THREAD

**Issue by ppcharli** [JohnSully/KeyDB#144]
Is it planned to do the  rpm for Centos8?
Is there any estimated date?

Thanks,

**Comment by JohnSully** [comment]
We're in the final phases of testing and should have it out in the next few days.

**Comment by benschermel** [comment]
Sorry for the delay here, we originally made rpm packages for Centos7 only. Per your request we have now added Centos8 rpm packages as well which will be supported moving forwards.

https://keydb.dev/downloads.html
