### ISSUE TITLE
KeyDB does not respect the maxclients config

### ISSUE THREAD

**Issue by hmashudi** [JohnSully/KeyDB#147]
Hello,

We are facing error during load test keydb server using memtier with clients more than 10K, the error was seems the keydb only respect the default value of [CONFIG_DEFAULT_MAX_CLIENTS](https://github.com/JohnSully/KeyDB/blob/RELEASE_5/src/server.h#L256) instead of value from config file.

**LOG Line**

```
738:M 27 Feb 2020 12:08:10.910 # Error registering fd event for the new client: Numerical result out of range (fd=10128)
738:M 27 Feb 2020 12:12:10.014 # Error registering fd event for the new client: Numerical result out of range (fd=10128)
738:M 27 Feb 2020 12:12:24.957 # Error registering fd event for the new client: Numerical result out of range (fd=10128)
```

**To Reproduce**

run keydb with the following command to expect maxclients is 40K:
```
keydb-server --port 6379 --server-threads 2 --server-thread-affinity false --protected-mode no --maxclients 40000
```
To confirm the config loaded:
```
$ keydb-cli config get maxclients
1) "maxclients"
2) "40000"
```

test using memtier with the following command to open 12K connections

```
memtier_benchmark --server <server_ip> --hide-histogram --ratio 0:1 -c 1000 -t 12 --out-file=s1_t1.out --test-time 300
```

**System info**
we use `n2-highmem-4` on gce instance with keydb compiled under Debian 9.12

keydb version:
```
$ keydb-server --version
Redis server v=5.3.1 sha=f4319c12:0 malloc=jemalloc-5.1.0 bits=64 build=47182d8b1c57e148
```

max open files on system was set to 65535 to make sure we are running enough of file descriptors
```
$ ulimit -Hn
65535
$ ulimit -Sn
65535
```

Tried to compile with change of the default [CONFIG_DEFAULT_MAX_CLIENTS](https://github.com/JohnSully/KeyDB/blob/RELEASE_5/src/server.h#L256) to let say 40K it was able to serve 12K clients/connections with no errors.

**Comment by JohnSully** [comment]
Fixed in change 54c96d19

We initialized the thread's event loop before we read the configuration file, so it always used the default maxclients.
