### ISSUE TITLE
`COMMAND INFO` command returns 7 rows instead of 6

### ISSUE THREAD

**Issue by budipang** [JohnSully/KeyDB#149]
**Describe the bug**
`COMMAND INFO` command returns 7 rows instead of 6(similar to redis) and according to KeyDB doc (https://docs.keydb.dev/docs/commands/#command)

```
127.0.0.1:6379> command info get
1) 1) "get"
   2) (integer) 2
   3) 1) readonly
      2) fast
   4) (integer) 1
   5) (integer) 1
   6) (integer) 1
   7) 1) @read
      2) @string
      3) @fast
```
**To Reproduce**
1. run COMMAND INFO GET on keydb-cli / redis-cli

**Comment by JohnSully** [comment]
Additional information from chat:

@JohnSully so my code uses https://github.com/go-redis/redis this as the redis cluster client, this particular client use COMMAND to retrieve the cluster metadata, the additional annotation break this client, made this client to request COMMAND metadata for every operation call

**Comment by JohnSully** [comment]
This is a change from upstream Redis, but regardless client code should be able to handle additional information returned from this command.  You'll need to update your library to support Redis 6 as well as KeyDB.  

I've communicated the issue to Antirez and I think we both agree that this shouldn't be fixed on our side.
