### ISSUE TITLE
[Question] compatibility with php-redis ?

### ISSUE THREAD

**Issue by durzo** [JohnSully/KeyDB#151]
I have read the documentation and FAQ but it's not clear whether keydb is compatible with redis client libraries or if we absolutely must use the keydb client.

We communicate with redis via the php-redis library. is there a php-keydb client library, or will the php-redis client work?

**Comment by JohnSully** [comment]
You can use any Redis library with KeyDB. They may not directly support new commands like EXPIREMEMBER or KEYDB.CRON but most have a facility to send unknown commands. 

The redis CLI will work fine. It just won’t have autocompletion for the above mentioned commands.

**Comment by durzo** [comment]
Thank you.
