### ISSUE TITLE
INCRBY and EXPIRE

### ISSUE THREAD

**Issue by silviucpp** [JohnSully/KeyDB#156]
**Is your feature request related to a problem? Please describe.**

When you are using counters most of the time you need to expire then after a certain time. In this moment the only solution I know is: 

1. call INCRBY
2. if result returned is equal with the initial value (a record was created) call expire

**Describe the solution you'd like**

Will be nice to have support to do all of the following in one single command. Basically to apply expire only in case the record was created with the initial value. If you put both in a transaction expire will execute all the time and will update the TTL

Silviu

**Comment by silviucpp** [comment]
This problem was also described here: https://redis.io/commands/incr#pattern-rate-limiter-2 and the solution to avoid the race condition where INCRBY was executed and expire no was to use a LUA script via eval.. which sucks form a performance point of view.

```
FUNCTION LIMIT_API_CALL(ip):
current = GET(ip)
IF current != NULL AND current > 10 THEN
    ERROR "too many requests per second"
ELSE
    value = INCR(ip)
    IF value == 1 THEN
        EXPIRE(ip,1)
    END
    PERFORM_API_CALL()
END

```

**Comment by JohnSully** [comment]
I was going to ask if LUA was a suitable solution, and it looks like you've answered that.

**Comment by silviucpp** [comment]
Lua decreases performance a lot, and this kind of counting it's very useful in lot of situations.
Not sure the original author of redis didn't implemented this..

**Comment by JohnSully** [comment]
I'm wondering if there is a way to make this more general, like an option to the EXPIRE command to only set it if there isn't already an expiration.

**Comment by silviucpp** [comment]
this might work as well :)

**Comment by silviucpp** [comment]
You will consider implementing this in the near future ?

**Comment by JohnSully** [comment]
Yes.  Just trying to think of a good name for the command.

**Comment by silviucpp** [comment]
I think adding an additional param to `INCR` called 'EX' like in `SET` it's an elegant solution.
And also adding `NX` param to `EXPIRE` command can be a good alternative if you want to mage expire more generic. When using `NX` expire won't be applied if the key already has an expire.

What do you think ?
Silviu

**Comment by JohnSully** [comment]
@silviucpp 

I've decided that KeyDB's CRON command is a more suitable workaround for this.  You'll be able to trigger a script on a schedule and make your own decision on whether to delete or keep the key.

**Comment by silviucpp** [comment]
I didn't believed that implemented expire for INCR is so complicated. This workaround seems very ugly..
