### ISSUE TITLE
Centos7 update to 5.3.3 replace /etc/keydb/keydb.conf

### ISSUE THREAD

**Issue by anadion** [JohnSully/KeyDB#161]
**Lost my keydb.conf**
I've update keydb-5.3.2-2.el7.x86_64.rpm to keydb-5.3.3-1.el7.x86_64 by yum install command.
And new version of keydb replace my /etc/keydb/keydb.conf without /etc/keydb/keydb.conf.rpmsave copy

**To Reproduce**
1. Install  keydb-5.3.2-2.el7.x86_64.rpm by 
```yum install https://download.keydb.dev/packages/rpm/centos7/x86_64/keydb_all_versions/keydb-5.3.2-2.el7.x86_64.rpm```
2. Edit your config `/etc/keydb/keydb.conf`
3. Update to keydb-5.3.3-1.el7.x86_64 by
```yum install https://download.keydb.dev/packages/rpm/centos7/x86_64/keydb_all_versions/keydb-5.3.3-1.el7.x86_64.rpm```
4. You lost you config

**Comment by benschermel** [comment]
Hi @anadion , thanks for pointing this out. 

I have updated the rpm spec files in our builders to ensure existing config files are not replaced. The following line has been added which has resolved this issue: `%config(noreplace) /etc/keydb/*` while removing line from `%files`

Another rpm build has been published reflecting this as "5.3.3-2" or "6.0.3-2". You can install the new build for your machine with:

yum install https://download.keydb.dev/packages/rpm/centos7/x86_64/keydb_all_versions/keydb-5.3.3-2.el7.x86_64.rpm

All builds moving forwards will retain config files.
