### ISSUE TITLE
maxsize not working with active-replica

### ISSUE THREAD

**Issue by jtorkkel** [JohnSully/KeyDB#164]
maxsize configuration not honored in active-replication. Seems that maxsize value ignored when "--active-replica yes" set.
Same problem also in multi-master. 

**Impact:** 
In Active replication DB size might accidentally increase until OOM or system start to swap due low memory. 
Becomes issue when one instance is restarted because up to 4x memory is needed due RDB sync. If DB is too large also restarting takes very long time or might fails resulting never ending loop (setting "client-output-buffer-limit replica 0 0 0" prevent failure in case enough memory available).
Seems that in active-replica the instance restart is issue for large DB in general and maxsize should be used to limit the DB size to reasonable size. 

**Repro steps:**
Start keydb locally with the following parameters.

/usr/bin/keydb-server --port 8881 --active-replica yes --replicaof 127.0.0.1 8882 --maxmemory 100mb --maxmemory-policy allkeys-lru

No need to start "replica/another instance", same result. Check from info that max size is correctly set. Fill DB with more entries than should fit to 100mb. For example 1M keys with 2KB vales. 

Result: DB will have 1M entries and consume more than 2GB based on info.
Expected result: max 100MB allocated to DB resulting rougly 5000 x 2kb keys.

**Working setup:**
if you remove active replication the maxsize is honored and info indicate used memory/number of keys is limited.
/usr/bin/keydb-server --port 8881 --maxmemory 100mb --maxmemory-policy allkeys-lru

Environment:
Windows 10/Ubuntu

**Comment by JohnSully** [comment]
Fixed with change: f112c77f.  The original test at the start of the eviction code was too strict.
