### ISSUE TITLE
Write performance of a master dropped sharply when a slave is added

### ISSUE THREAD

**Issue by hengku** [JohnSully/KeyDB#169]
When deploying a KeyDB 5.3.1 Master-Slave pair, I noticed the master's writing performance dropped sharply. The QPS is 115K (single master) VS 80K (master-slave); the latency is 0.429ms VS 0.619ms. The reading performance seems no significant drop.

**Comment by JohnSully** [comment]
@hengku I don't repro the severity of your drop, nonetheless I have significantly improved the performance of replication in the unstable branch with changes:
8e81e5f29e718395b32a60ff263808305d0b5818
63dd1fb599cfe959c0298825ed56ab06335b3fd7
32561a99124542461de283d5035f869b5fc9bc2f

Can you let me know if this improves on your system?  I see an improvement of 12% and verified performance is similar to Redis in this scenario (single threaded).

**Comment by hwware** [comment]
Thank you, John, I will re-verify this shortly and let you know the results.

**Comment by hengku** [comment]
Thank you, John, I will re-verify this shortly and let you know the results.

**Comment by hengku** [comment]
Hi John, I re-tested and verified your fix. It works, thank you! Here are some details: 

* Binary before fix (3fdc860): 

QPS is 142K (single master) vs 99K (master-slave) - 31% decreased

Latency is 0.35ms VS 0.5ms - 43% increased

* Binary after fix (e726426): 

QPS is 139K (single master) vs 130K (master-slave) - 7% decreased 

Latency is 0.36ms vs 0.38ms - 6% increased

**Comment by JohnSully** [comment]
Closing as fixed
