### ISSUE TITLE
debian source packages

### ISSUE THREAD

**Issue by tchernomax** [JohnSully/KeyDB#171]
**Describe the bug**
As deb packages are currently build against ubuntu they are not safe to use on pure debian.
I planed to rebuild the deb packages on debian but didn't found the deb sources.

`deb-src https://download.keydb.dev/keydb-ppa ./` doesn't works.
https://download.keydb.dev/ and https://download.keydb.dev/keydb-ppa/ are 403 forbidden.

Didn't found it either in the git sources.

Where can I find them ?

**To Reproduce**

```
# echo 'deb-src https://download.keydb.dev/keydb-ppa ./' > /etc/apt/sources.list.d/keydb.list
# apt update
…
W: Skipping acquire of configured file 'Sources' as repository 'https://download.keydb.dev/keydb-ppa ./ InRelease' does not seem to provide it (sources.list entry misspelt?)
```

**Comment by benschermel** [comment]
You can now find debian package source directories under pkg/deb (currently in unstable branch).  (https://github.com/JohnSully/KeyDB/tree/unstable/pkg/deb/debian).

I have added in stretch and buster debian packages that we will continue to maintain and support. You can find the debian stretch and buster packages in keydb downloads https://download.keydb.dev/packages/deb/
