### ISSUE TITLE
ppa KEY.gpg wrong format

### ISSUE THREAD

**Issue by tchernomax** [JohnSully/KeyDB#172]
**Describe the bug**
`apt-key add` is deprecated.

https://manpages.debian.org/stretch/apt/apt-key.8.en.html

> Note: Instead of using this command a keyring should be placed directly in the /etc/apt/trusted.gpg.d/ directory with a descriptive name and either "gpg" or "asc" as file extension.

"https://download.keydb.dev/keydb-ppa/KEY.gpg" is armored so it can't be place directly to `/etc/apt/trusted.gpg.d/`.

Please provide a KEY.asc or dearmor KEY.gpg.

**To Reproduce**

```
# curl -s --compressed -o /etc/apt/trusted.gpg.d/keydb.gpg https://download.keydb.dev/keydb-ppa/KEY.gpg
# apt update
…
W: http://ftp2.fr.debian.org/debian/dists/buster/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/keydb.gpg are ignored as the file has an unsupported filetype.
```

**Comment by benschermel** [comment]
Hi @tchernomax 

Thanks for bringing this up. I have added a non-ASCII armored key "keydb.gpg" to the ppa repo which can be added with:
```
$ sudo curl -s --compressed -o /etc/apt/trusted.gpg.d/keydb.gpg https://download.keydb.dev/keydb-ppa/keydb.gpg
```
KEY.gpg armored key still exits for those who may be using scripts, however I will update our docs shortly with the updated method of placing keydb.gpg in /etc/apt/trusted.gpg.d/

**Comment by tchernomax** [comment]
Thanks !
I think we can close this issue when the documentation https://docs.keydb.dev/docs/ppa-deb/ will be updated.

**Comment by benschermel** [comment]
Closing issue, documentation related to PPAs has been updated
