### ISSUE TITLE
Clang fails to compile KeyDB with a linker error

### ISSUE THREAD

**Issue by lazerl0rd** [JohnSully/KeyDB#173]
**Describe the bug**

Clang fails to compile with the error is shown below:

```make
ld.lld: error: undefined symbol: __atomic_fetch_add_2
>>> referenced by sds.c:185
>>>               lto.tmp:(sdsdupshared)
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:276: keydb-server] Error 1
```

**To Reproduce**

```
export CC="clang"
export CXX="clang++"

CFLAGS="-flto=thin -fno-plt -march=native -mtune=native -O3 -pipe"
CXXFLAGS="-flto=thin -fno-plt -march=native -mtune=native -O3 -pipe"
LDFLAGS="-fuse-ld=lld -Wl,--as-needed,-O1,--sort-common,-z,now,-z,relro"

git clone https://github.com/JohnSully/KeyDB.git
make BUILD_TLS=yes -C "KeyDB"
```

**Comment by JohnSully** [comment]
Thanks! 

I need to do a few more tests before merging. This atomic lib has caused no end of grief. So platforms need. Some don’t care and others can’t have it all.

**Comment by lazerl0rd** [comment]
@JohnSully I only skimmed over the code, but the file `src/sds.c` doesn't seem to provide an alternative to not using libatomic.

**Comment by JohnSully** [comment]
In some cases its using compiler builtins and therefore not dependent on an external library. Initially I was unconditionally linking libatomic but that caused build failures with GCC on ARM (didn’t test clang). 

Your change appears fine, just needs to be validated on ARM. I’ll have it merged soon.

**Comment by lazerl0rd** [comment]
@JohnSully I'm a bit busy ATM for this one, but a hint on memkind that it fails with Clang too.
