### ISSUE TITLE
ACL: support #<hash>

### ISSUE THREAD

**Issue by tchernomax** [JohnSully/KeyDB#178]
redis support providing the password as hash, so the password doesn't appear in clear text:

https://redis.io/topics/acl#acl-rules

> #<hash>: Add this SHA-256 hash value to the list of valid passwords for the user. This hash value will be compared to the hash of a password entered for an ACL user. This allows users to store hashes in the acl.conf file rather than storing cleartext passwords. Only SHA-256 hash values are accepted as the password hash must be 64 characters and only container lowercase hexadecimal characters.
> !<hash>: Remove this hash value from from the list of valid passwords. This is useful when you do not know the password specified by the hash value but would like to remove the password from the user.

It would be great if keydb also support this feature.

**Comment by JohnSully** [comment]
Hi @tchernomax This is  a Redis 6.0 feature which we're about to release in KeyDB 6.  I verified in the usntable branch and this feature is now working there.
