### ISSUE TITLE
Client hangs when it issues "CLIENT TRACKING ON" command

### ISSUE THREAD

**Issue by surenkajan** [JohnSully/KeyDB#181]
**Describe the bug**
Client hangs when it issues "CLIENT TRACKING ON" command in client side caching use case. 

**To Reproduce**
1. Start the KeyDB-Server (I am using KeyDB 5.3.3 binary)
2. Start Client-01 (telnet client)
3. Client-01 enables RESP-3 by issuing "hello 3" command
4. Client-01 issues "CLIENT TRACKING ON" command to enable tracking

Client-01 hangs at 4th step.

Same error happens when I try the client side caching using RESP2 mode.

**Comment by JohnSully** [comment]
Hi @surenkajan This is fixed in unstable and will be fixed in our first 6.0 release.  Redis 6.0 features were unstable in our 5 series branch.

**Comment by surenkajan** [comment]
Thanks Johh. I will re-test this in 6.0 release.
