### ISSUE TITLE
KeyDB-Server with TLS Support

### ISSUE THREAD

**Issue by surenkajan** [JohnSully/KeyDB#184]
KeyDB-Server cannot run with TLS mode eventhough  it is built with TLS support. 

** Log Files **
```
*** FATAL CONFIG FILE ERROR (Redis 0.0.0) ***
Reading the configuration file, at line 2
>>> 'tls-port "8001"'
Bad directive or wrong number of arguments
```

**To Reproduce**

1. Builds KeyDB-Server with TLS support (make BUILD_TLS=yes)
2. Run ./utils/gen-test-certs.sh to generate a root CA and a server certificate
3. Manually run a KeyDB server with TLS mode

```
    ./src/keydb-server --tls-port 8000 --port 0 \
    --tls-cert-file ./tests/tls/redis.crt \
    --tls-key-file ./tests/tls/redis.key \
    --tls-ca-cert-file ./tests/tls/ca.crt
```
   
**Binary Version:**
KeyDB-server binary is built from unstable branch (Commit hash: 3543a3c)

**Comment by JohnSully** [comment]
Hi @surenkajan 

Redis 6.0 features aren't available in 5.0 versions.  We're releasing our first 6.0 release tomorrow which will have working TLS.

**Comment by JohnSully** [comment]
It should be enabled with change: d05da0fab

**Comment by surenkajan** [comment]
Thanks John. I will re-test this feature in 6.0 release.
