### ISSUE TITLE
Unexpected crash, I suspect EXPIREMEMBER

### ISSUE THREAD

**Issue by slash4** [JohnSully/KeyDB#189]
Hi ! We use keydb as a drop in replacement of REDIS since weeks now, and everything was right, until this morning, we experienced a massive crash, and since, keydb crashes from time to time, we use the containerized version. 

** Log Files **
keydb_1_98b156b130e6 | keydb-server: semiorderedset.h:324: bool semiorderedset<T, T_KEY, MEMMOVE_SAFE>::enumerate_bucket(semiorderedset<T, T_KEY, MEMMOVE_SAFE>::setiter&, const T_MAX&, T_VISITOR&, long long int*) [with T_VISITOR = activeExpireCycle(int)::<lambda(expireEntry&)>; T_MAX = long long int; T = expireEntry; T_KEY = const char*; bool MEMMOVE_SAFE = true]: Assertion `(itr.idxSecondary+1) >= vec.size() || static_cast<T_MAX>(vec[itr.idxSecondary]) <= static_cast<T_MAX>(vec[itr.idxSecondary+1])' failed.
keydb_1_98b156b130e6 |
keydb_1_98b156b130e6 |
keydb_1_98b156b130e6 | === KEYDB BUG REPORT START: Cut & paste starting from here ===
keydb_1_98b156b130e6 | 1:15:M 04 Jun 2020 13:46:30.985 # KeyDB 5.3.3 crashed by signal: 11
keydb_1_98b156b130e6 | 1:15:M 04 Jun 2020 13:46:30.985 # Crashed running the instruction at: 0x7f441fa8f8f0
keydb_1_98b156b130e6 | 1:15:M 04 Jun 2020 13:46:30.987 # Accessing address: (nil)
keydb_1_98b156b130e6 | 1:15:M 04 Jun 2020 13:46:30.987 # Failed assertion: <no assertion failed> (<no file>:0)
keydb_1_98b156b130e6 |
keydb_1_98b156b130e6 | ------ STACK TRACE ------
keydb_1_98b156b130e6 | EIP:
keydb_1_98b156b130e6 | /lib/x86_64-linux-gnu/libc.so.6(abort+0x230) [0x7f441fa8f8f0]
keydb_1_98b156b130e6 |
keydb_1_98b156b130e6 | Backtrace:
keydb_1_98b156b130e6 | keydb-server *:6379(logStackTrace(ucontext_t*)+0x6b) [0x55a51657e66b]
keydb_1_98b156b130e6 | keydb-server *:6379(sigsegvHandler(int, siginfo_t*, void*)+0xc9) [0x55a51657ee09]
keydb_1_98b156b130e6 | /lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f441fe52890]
keydb_1_98b156b130e6 | /lib/x86_64-linux-gnu/libc.so.6(abort+0x230) [0x7f441fa8f8f0]
keydb_1_98b156b130e6 | /lib/x86_64-linux-gnu/libc.so.6(+0x3039a) [0x7f441fa7f39a]
keydb_1_98b156b130e6 | /lib/x86_64-linux-gnu/libc.so.6(+0x30412) [0x7f441fa7f412]
keydb_1_98b156b130e6 | keydb-server *:6379(activeExpireCycle(int)+0x513) [0x55a5165b8df3]
keydb_1_98b156b130e6 | keydb-server *:6379(databasesCron()+0x38) [0x55a516522e18]
keydb_1_98b156b130e6 | keydb-server *:6379(serverCron(aeEventLoop*, long long, void*)+0x28c) [0x55a516525d7c]
keydb_1_98b156b130e6 | keydb-server *:6379(aeProcessEvents+0x25b) [0x55a51651d87b]
keydb_1_98b156b130e6 | keydb-server *:6379(aeMain+0x45) [0x55a51651db55]
keydb_1_98b156b130e6 | keydb-server *:6379(workerThreadMain(void*)+0x97) [0x55a5165220c7]
keydb_1_98b156b130e6 | /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f441fe476db]
keydb_1_98b156b130e6 | /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f441fb7088f]
keydb_1_98b156b130e6 |
keydb_1_98b156b130e6 | ------ INFO OUTPUT ------
keydb_1_98b156b130e6 | # Server
keydb_1_98b156b130e6 | redis_version:5.3.3
keydb_1_98b156b130e6 | redis_git_sha1:07cb1f45
keydb_1_98b156b130e6 | redis_git_dirty:0
keydb_1_98b156b130e6 | redis_build_id:fbc288a87c98cc19
keydb_1_98b156b130e6 | redis_mode:standalone
keydb_1_98b156b130e6 | os:Linux 5.0.0-1025-gcp x86_64
keydb_1_98b156b130e6 | arch_bits:64
keydb_1_98b156b130e6 | multiplexing_api:epoll
keydb_1_98b156b130e6 | atomicvar_api:atomic-builtin
keydb_1_98b156b130e6 | gcc_version:7.4.0
keydb_1_98b156b130e6 | process_id:1
keydb_1_98b156b130e6 | run_id:4733bb0cdcbaff59d8c4070e9ccc8c8d92625311
keydb_1_98b156b130e6 | tcp_port:6379
keydb_1_98b156b130e6 | uptime_in_seconds:13338
keydb_1_98b156b130e6 | uptime_in_days:0
keydb_1_98b156b130e6 | hz:10
keydb_1_98b156b130e6 | configured_hz:10
keydb_1_98b156b130e6 | lru_clock:14220086
keydb_1_98b156b130e6 | executable:/data/keydb-server
keydb_1_98b156b130e6 | config_file:/etc/keydb/keydb.conf

I suspect EXPIREMEMBER as it is the only "new" feature we introduced recently. I cannot read clearly what's happening, do I use it right ? 

Thanks a lot, Alex

**Comment by JohnSully** [comment]
Hi @slash4 

Sorry about this bug, it occurs when a set, hash or zset element is deleted while a subkey expire is set.  The code to handle this case did not correctly adjust the expire set.  We did have a test for this case but due to timing issues it didn't hit the specific buggy code path.  

Change c6dce838b7cc94e115fd73a64dda663f0a2c28c5 fixes the issue, while 0042586190a3e5b212a015aeb3577695cd3623c5 adds a test to detect it.
