### ISSUE TITLE
[Q] keys scan command

### ISSUE THREAD

**Issue by hellower** [JohnSully/KeyDB#19]
REDIS warning..
..........................................
When the number of keys in redis (use DBSIZE to know the count) is less, this method can be used but when redis size grows, using keys cmd is extremely dangerous for performance and highly discouraged in production environment since redis is single threaded, keys cmd will block all other operations on redis and all the clients will have to wait for its completion.
..........................................

 Is KeyDB subject to the same constraints or not ?

**Comment by JohnSully** [comment]
While KeyDB is Multithreaded the Keys command will hold a lock for the duration of its execution. This has the same issues as with Redis. 

We are looking into allowing lock free execution of commands and I will add this to the list of things to look at. 

In short yes - it has the same issue but for a different reason.

**Comment by hellower** [comment]
Thanks.

**Comment by JohnSully** [comment]
Sorry we couldn’t help you. I’ll update this issue  if we are able to improve Keys in the future.
