### ISSUE TITLE
Multi-Master - Removing a down node

### ISSUE THREAD

**Issue by jameswestover** [JohnSully/KeyDB#192]
When running KeyDB in a multi-master setup, if a master fails and is unable to reacquire the same address upon startup, the node moves into a `master_link_status:down` state. It would be nice to be able to remove the bad replica without having to restart the KeyDb process. 

`REPLICAOF NO ONE` removes all nodes, in which case the healthy nodes would have to be added back in, causing a lapse in replication / availability. 

It would be nice to have a command something like `REPLICAOF REMOVE IP PORT` which would remove a master from the replication group.  

I haven't found an alternative that allows removing nodes in a zero down time way, while still retaining the other health replication members.

**Comment by JohnSully** [comment]
Yes I agree that's a major missing feature.

I've implemented it exactly as you described in change: 70b80aa5f

**Comment by jameswestover** [comment]
Amazing! Thank you!

**Comment by darinspivey** [comment]
Wow, I'm super glad I found this issue as I was getting ready to implement `replicaof no one` to remove dead replicas.  Thank you for this fix, but the documentation desperately needs to be updated to reflect this feature.

I opened #412 for this, and THANK YOU for this fix which I can immediately use!
