### ISSUE TITLE
Bad directive or wrong number of arguments error on 'lazyfree-lazy-user-del no'

### ISSUE THREAD

**Issue by hengku** [JohnSully/KeyDB#194]
I tried to start a KeyDB server (6.0.8 RC) by using the default keydb.conf, but it failed and threw the error below: 

*** FATAL CONFIG FILE ERROR (Redis 6.0.8) ***
Reading the configuration file, at line 971
>>> 'lazyfree-lazy-user-del no'
Bad directive or wrong number of arguments

**Comment by JohnSully** [comment]
Merge bug with Redis, this is fixed in change f111c234152fd47d21c8c95029bcb191641182a7
