### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [JohnSully/KeyDB#2]
Would you like to add more error handling for return values from functions like the following?
- [pthread_cond_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_init.html "Initialize condition variables.") ⇒ [bioInit](https://github.com/JohnSully/KeyDB/blob/40d7a701feefd36e9e3fdb6d516228c4a70fcf3d/src/bio.c#L95)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [initServerConfig](https://github.com/JohnSully/KeyDB/blob/ffabf3c5b7efa5ec6b654d8d8f5f11a86b39c8cd/src/server.c#L2250)

**Comment by JohnSully** [comment]
This issue has been fixed.  All failures are fatal and treated as such.

Thank you!

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to [detect every error situation](https://github.com/JohnSully/KeyDB/blob/01a529cbda919d5514a4a445b26a0408115173ca/src/bio.c#L131 "Update candidate: bioCreateBackgroundJob()") as early as possible?
