### ISSUE TITLE
[Feature request ] MEXISTS - multi exists

### ISSUE THREAD

**Issue by gittyup2018** [JohnSully/KeyDB#203]
While EXISTS is useful for one or 2 keys, if there are 3+ keys and one or more is missing, 
there is currently no way to tell which key is missing as it only returns a number of keys that exist.

MEXISTS would take an array of keys and return 0,1 in order

SET k1 val
SET k3 val

MEXISTS k1 k2 k3 would return [1,0,1] so now you know middle key is missing and is much more useful than just returning a number.

**Comment by JohnSully** [comment]
Hi @gittyup2018 I really like this idea, I've implemented it in change 5619f515

It will be in the next release.

127.0.0.1:6379> keydb.mexists A B C D
1) (integer) 1
2) (integer) 0
3) (integer) 1
4) (integer) 0
