### ISSUE TITLE
Timeout when using RediSearch and keyDB

### ISSUE THREAD

**Issue by tscott1995** [JohnSully/KeyDB#209]
I am running keyDB and RediSearch on Ubuntu. I have the newest version of both installed and running on my machine. My problem is whenever I run the commands:
-FT.CREATE myIdx SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT
-FT.ADD myIdx doc1 1.0 FIELDS title "hello world" body "lorem ipsum" url "http://redis.io" 
-FT.ADD myIdx doc2.0 FIELDS title "test data" body "for keyDB" url "https://yahoo.com"
I get a timeout after I try adding the second document and cannot continue to use keyDB without a restart. I referred back to Issue #27 and didn't see a true fix there.

**Comment by francisco-batista-wize** [comment]
It is something related with RedisSearch's grarbage collector. If you disable it, the problem dissapears, but I don't know if it is a good idea to disable GC, so consider it a workarround.

**Comment by JohnSully** [comment]
This is fixed in change: e0131264

RediSearch uses the experimental module API which has an async lock API.  We deadlocked when this was called from a server thread as part of a module callback.  I've added a test to detect this case.
