### ISSUE TITLE
Could not connect to Redis when choosing a non-default port

### ISSUE THREAD

**Issue by LZL0** [JohnSully/KeyDB#21]
Upon configuring KeyDB to use a non-default port the following error occurs:

```
$ keydb-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected>
```
In this instance I am using `6366` but it tries to connect to `6379` as shown above.
I've set the port to `6366` when running `install_sever.sh` and the config file contains the following:
`port 6366`
KeyDB is running in the background just fine and my website happily uses it through port `6366`.

OS: Ubuntu 16.04

**Comment by JohnSully** [comment]
The issue is that you haven't told keydb-cli which port to connect to, so its trying the default.  Use:

    keydb-cli -p 6366

**Comment by LZL0** [comment]
Thank you!

**Comment by JohnSully** [comment]
Happy to help!
