### ISSUE TITLE
Issue in multi-master feature. Keydb is dropping local data.

### ISSUE THREAD

**Issue by hrkgarg** [JohnSully/KeyDB#210]
Hi,

We are trying to use multi-master feature of keydb on our lab-environment.

We have a centralized keydb-cluster running with three master nodes and three slave nodes. 

To reduce the latency at our client software, we need a copy of complete data on our local machine; thereby treating local-keydb server as primary data-bank and centralized cluster as secondary data-bank in case of outage of local-server instance. 

Thus, we have installed a keydb-server on local machine; started it in multi-master mode and made it replica of all three nodes of cluster.

Local server is able to :
    **1.** Connect with all three nodes of cluster. 
    **2.** Once it is connected, if any entry is added/modified/deleted from cluster, that change is also getting reflected on the local-keydb server.

However, if data is already present in the cluster nodes (Which mostly be the case), then local-dataset is having issues.

### Issue-1 
**Expected behavior as per documentation** : Local server should get data from all 3 nodes of cluster and create complete data at its end at startup.
**Actual behavior** : When we start local-keydb-server from dead-start, then local-keydb-server is showing data only from the cluster node server written at last position in the **replicaof** list. So effectively, local-keydb-server has only 33% of total data, which remains the case for its life-time. We believe it has dropped data-set received from the other two cluster-nodes while applying the data-set received from the third node.

### Issue-2
Because the centralized cluster has a slave cluster containing three slave-nodes corresponding to the three masters, So we are expecting local keydb-server to automatically switch to corresponding slave node when a master-node from cluster goes down and corresponding slave is promoted to master. However, that also is not happening

**Servers : RHEL-7.7
Keydb-RPM : keydb-6.0.9-1.el7.x86_64.rpm (From _https://download.keydb.dev/packages/rpm/centos7/x86_64/keydb_all_versions/_)**

Thanks,
Himanshu

**Comment by hrkgarg** [comment]
Hi @JohnSully ,

We are eagerly for your inputs on this issue.

Regards,
Himanshu

**Comment by JohnSully** [comment]
Hi @hrkgarg 

If my understanding is correct you have a traditional Redis style cluster sharded across 3 masters with 1 replica per master.  Secondly you plan to have one single node that has a superset of the entire dataset.  I've drawn the diagram to show my understanding.

![image](https://user-images.githubusercontent.com/3894786/87235222-0724dd80-c3a8-11ea-80e5-55281e44d36c.png)

This is a very unusual topology however Issue #1 should work as you expect.  I will investigate this further.

For Issue #2 you need some external coordination to ensure this happens.  Multimaster is not intended to cooperate with clusters which is considered a completely separate operating mode. Making multi-master handle this scenario is considered out of scope for the feature.  If you require this behavior you'd need to write an external tool to perform the failover by sending KeyDB the necessary replicaof commands.

**Comment by JohnSully** [comment]
Issue #1 is a super bad bug with Active Replication.  It was introduced with the merge of Redis 6.
Fixed in change cd9514f4 along with a test to catch this in the future.
