### ISSUE TITLE
RPM packages should be signed

### ISSUE THREAD

**Issue by xmikew** [JohnSully/KeyDB#211]
The CentOS rpms are not signed. installing requires --nogpgcheck and it would make me sleep better at night if I knew I was installing code signed by the developers. There has been cases historically of packaged software being modified. Having gpg checks can help detect that for users of the software.

Looks like the deb packages are signed, why not rpms?

Thanks much,

\- Mike

**Comment by benschermel** [comment]
Hi @xmikew , signing is now added for RPM packages. All versions 6.0.13 and higher will now contain signatures. I have updated docs to reflect this also: https://docs.keydb.dev/docs/rpm/ 

You can import the public key with:
```
$ rpm --import https://download.keydb.dev/packages/rpm/RPM-GPG-KEY-keydb
```
