### ISSUE TITLE
CentOs 7 files have execution bit set for various configuration files

### ISSUE THREAD

**Issue by in-journey** [JohnSully/KeyDB#212]
**Describe the bug**
Hi, these files have execution bit set when installing from RPM - just installed version 6.0.9 on CentOs 7:
/etc/logrotate.d/keydb
/etc/keydb/keydb.conf
/etc/keydb/keydb-sentinel.conf
/usr/lib/systemd/system/keydb.service
/usr/lib/systemd/system/keydb-sentinel.service
/etc/systemd/system/keydb.service.d/limit.conf
/etc/systemd/system/keydb-sentinel.service.d/limit.conf

Stat example:
```
# stat /etc/logrotate.d/keydb
  File: ‘/etc/logrotate.d/keydb’
  Size: 127             Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 526189      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:etc_t:s0
Access: 2020-06-24 07:20:33.000000000 +0200
Modify: 2020-06-24 07:20:33.000000000 +0200
Change: 2020-07-02 10:31:36.171070617 +0200
 Birth: -
```
This actually prevents logrotate from working (it skips rotating KeyDB logs). As for service files, you can see warning messages in system log but it actually works.
I don't know if there are any more files with executable bit set (obviously except files in /bin) - I didn't look further into it. It might be worth to check them all. I also do not know if other distributions are infected by this.

Please remove execution bits for files that actually do not need it.

**To Reproduce**
Install latest rpm package for CentOs 7 and check files mentioned above for execution bit.

**Side question**

I noticed that version 6.0.9 is not listed on releases page (https://github.com/JohnSully/KeyDB/releases) - is it RC2?

**Comment by benschermel** [comment]
Hi @in-journey, 

Thanks for pointing this out, I believe this changed when migrating the builder code. I have now gone through all the files for Centos7/8 and updated the permissions accordingly. Should be fixed in current 6.0.13 builds and moving forwards.
