### ISSUE TITLE
RDB file is the double size of the one generated by Redis

### ISSUE THREAD

**Issue by hengku** [JohnSully/KeyDB#218]
For example, for a database with 2 millions keys (each value has 256 bytes), the RDB file generated by KeyDB is 136MB, but the one generated by Redis is 73MB. I observed this difference since KeyDB 5.x. Is that normal to KeyDB, or something wrong?

**Comment by JohnSully** [comment]
This is fixed for non-active replicas, the issue here is that active replicas require us to save out an AUX field for each key.  The RDB file format is not very efficient for AUX data.  We now only save this out if active replication is used.
