### ISSUE TITLE
Memory accumulates when running long lua scripts

### ISSUE THREAD

**Issue by JohnSully** [JohnSully/KeyDB#22]
The following script repeatedly sets a key to different values.  Memory grows quickly and excessively as the script is run (over many GB).  If the script is able to run to completion the memory is freed.

Script:
for i = 1, 10000000000, 1 do
redis.call("SET", "ZzZ_MYKEYZzZ"..i.."key", i)
end

Repro:
./keydb-cli --eval /tmp/bench.lua 

This behavior is particularly bad when FLASH backing is used as it leads to write amplification.

**Comment by lukensmall** [comment]
I'm wondering what application you could possibly have in which such a script could be useful. It's for scripts like that that you don't allow hackers to have access to your redis port

**Comment by JohnSully** [comment]
The bug isn't that this specific use case doesn't work, but rather that a cache is allowed to grow unbounded.  This can cause problems in real world use cases.

**Comment by JohnSully** [comment]
Misunderstanding of the script.  The underlying issue is that FLASH has little control over kernel paging and results in high levels of writes.  This will be fixed when we implement manual paging.
