### ISSUE TITLE
[Question] How to use EXPIREMEMBER  command with node.js client (node_redis) ... 

### ISSUE THREAD

**Issue by yxwu** [JohnSully/KeyDB#221]
I like KeyDB once I saw it. But I have a question:

I want to use the `EXPIREMEMBER` command, but seems node_redis doesn't support it, then how can I use it within my  node.js application? Is there any other node.js client for KeyDB available?

Any suggestions?

Thanks

**Comment by bpo** [comment]
Hi @yxwu, with node_redis you can add commands like so:

```
const redis = require("redis");
redis.add_command("expiremember");
```

to use...

```
const client = redis.createClient();
client.sadd("testkey", "a", "b", "c", redis.print)
// Reply: 3
client.smembers("testkey", redis.print)
// Reply: a,c,b
client.expiremember("testkey", "a", 1000, redis.print)
// Reply: 1
client.ttl("testkey", "a", redis.print)
// Reply: 998
```

hope that helps!

**Comment by yxwu** [comment]
Thanks @bpo, very helpful, I will give it a try!

**Comment by robertsteilberg** [comment]
I've found that this doesn't work when pipelining--specifically `EXPIREMEMBER``--is this a known issue?

**Comment by bpo** [comment]
@robertsteilberg can you be more specific about what you're trying, and expected/actual results?

**Comment by robertsteilberg** [comment]
My apologies--I was using the node client incorrect. 😅

**Comment by JohnSully** [comment]
Thanks @bpo !
