### ISSUE TITLE
io-threads-do-reads

### ISSUE THREAD

**Issue by sign0** [JohnSully/KeyDB#222]
**Describe the bug**

I just upgraded my keyDB to the latest version (v6.0.13) and found an issues with ```io-threads-do-reads``` setting in the keydb.conf file.

**Log Files**

```bash
*** FATAL CONFIG FILE ERROR (Redis 6.0.13) ***
Reading the configuration file, at line 1007
>>> 'io-threads-do-reads yes'
Bad directive or wrong number of arguments
```

**To Reproduce**

- update ```# io-threads-do-reads no``` to ```io-threads-do-reads yes``` in the keydb.conf file.

**Comment by JohnSully** [comment]
There was an earlier issue where this was in our default config file.  That was fixed a while ago, but we also need a dummy load to retain compatibility with redis config files even if this config is meaningless to us.

Fix change: 02b533fec
