### ISSUE TITLE
Fix keydb HAProxy configuration file example

### ISSUE THREAD

**Issue by tgiordmaina** [JohnSully/KeyDB#224]
Hello,

I'm a new user of your incredible project !

I created a multi-master cluster but I lost time to fix configuration because there are some issues in your HAProxy example configuration, could you provide me the github to fix this ?

Or could you do it if it's a private repo.

Here the change needed to get a fully valid HAProxy configuration file.
URL: https://docs.keydb.dev/docs/haproxy/
Replace `#tcp-check expect +OK` by `#tcp-check expect string +OK`
Replace `expect string role:acitve-replica` by `expect string role: acitve-replica`
Replace `tcp-check expect string role:master` by `tcp-check expect string role: master`

Best Regards,

Thomas

**Comment by benschermel** [comment]
Hi @tgiordmaina,

Good catch, and thanks for bringing this to our attention. It has been updated https://docs.keydb.dev/docs/haproxy/ 

Thanks!

Ben
