### ISSUE TITLE
ECONNREFUSED when running KeyDB via docker-compose with a keydb.conf file

### ISSUE THREAD

**Issue by robertsteilberg** [JohnSully/KeyDB#225]
**Describe the bug**
I am trying to build KeyDB with `docker-compose`. Here is my docker-compose YAML:

```
version: '3.8'
services:
  redis:
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    volumes:
      - $PWD/keydb.conf:/etc/keydb/keydb.conf
  express:
    build: .
    depends_on:
      - redis
    ports:
      - "80:80"
```

As you can see, I am configuring KeyDB with everything default except I am giving it a conf file that I intend to tweak some settings in. Right now, `keydb.conf` is directly copied from `keydb.conf` in the main KeyDB repo, so I wouldn't expect there to be any issues, since *running KeyDB via `docker-compose` without a conf file specified works just fine.* Upon startup, my application is unable to connect to KeyDB and fails with ECONNREFUSED, even though it successfully connects when there is no `keydb.conf` file given.

As suggested in keydb's Docker Hub page, I tried commenting out `bind 127.0.0.1` and disabling protected mode, but this did not resolve the issue.

** Log Files **
```
1:1:C 10 Aug 2020 16:16:48.249 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
1:1:C 10 Aug 2020 16:16:48.249 # KeyDB version=6.0.13, bits=64, commit=a6782a3c, modified=1, pid=1, just started
1:1:C 10 Aug 2020 16:16:48.249 # Configuration loaded                                                                                                                                                                                  

KeyDB 6.0.13 (a6782a3c/1) 64 bit
Running in standalone mode
Port: 6379
PID: 1
Join the KeyDB community! https://community.keydb.dev/       

1:1:M 10 Aug 2020 16:16:48.304 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:1:M 10 Aug 2020 16:16:48.304 # Server initialized
1:1:M 10 Aug 2020 16:16:48.304 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with KeyDB. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. KeyDB must be restarted after THP is disabled.
1:1:M 10 Aug 2020 16:16:48.304 * Loading RDB produced by version 6.0.13
1:1:M 10 Aug 2020 16:16:48.304 * RDB age 1 seconds
1:1:M 10 Aug 2020 16:16:48.304 * RDB memory usage when created 8.81 Mb
1:1:M 10 Aug 2020 16:16:48.306 * DB loaded from disk: 0.002 seconds1:21:M 10 Aug 2020 16:16:48.306   Thread 1 alive.1:20:M 10 Aug 2020 16:16:48.307   Thread 0 alive.
```

**To Reproduce**
1. Run KeyDB via `docker-compose` with a specified `keydb.conf` file
2. Try to access KeyDB in another container that depends on the KeyDB

**Comment by christianEQ** [comment]
I wasn't able to reproduce this, with or without a config file specified. Please ensure your server is running and that you're directing the client to the correct port. If you're still getting this issue, please update with some more info - what system you're running on, your Dockerfile, and the keydb.conf file (I know it's the default one, but just for completeness) would all be useful. 

KeyDB logs from both the client and server containers would also be helpful - you can run `docker logs <container>` to see the stdout from them.

**Comment by christianEQ** [comment]
Closing for now pending an update. We'll reopen the issue then.
