### ISSUE TITLE
With replica-serve-stale-data=no failure of any master makes all replicas unusable 

### ISSUE THREAD

**Issue by yegors** [JohnSully/KeyDB#232]
**Describe the bug**
If any of the available masters in a multi-master setup are not available, the healthy nodes become unusable with the error: `MASTERDOWN Link with MASTER is down and replica-serve-stale-data is set to 'no'.`

There should be some kind of threshold for this, since if you're talking to 3 different masters, and 1 of them goes down, that should not make the whole setup unusable, as that defeats the whole point of it. 

Here is the info output in this state. Notice `master_global_link_status = down`, even when 2/3 masters are still in fact up. 
```
# Replication
role:active-replica
master_global_link_status:down
Master 0:
master_host:1.1.1.1
master_port:46379
master_link_status:up
master_last_io_seconds_ago:6
master_sync_in_progress:0
slave_repl_offset:2833752
Master 1:
master_host:2.2.2.2
master_port:46379
master_link_status:up
master_last_io_seconds_ago:4
master_sync_in_progress:0
slave_repl_offset:2278353
Master 2:
master_host:3.3.3.3
master_port:46379
master_link_status:down
master_last_io_seconds_ago:-1
master_sync_in_progress:0
slave_repl_offset:492680
master_link_down_since_seconds:1314
slave_priority:100
slave_read_only:0
connected_slaves:2
slave0:ip=1.1.1.1,port=46379,state=online,offset=1384675406,lag=1
slave1:ip=2.2.2.2,port=46379,state=online,offset=1384675406,lag=1
master_replid:8624f5af2f4c1892a13dfabf7fbef4765af9184f
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:1384675406
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576000
repl_backlog_first_byte_offset:336099407
repl_backlog_histlen:1048576000
```

**To Reproduce**
1. Create a 3 node multi-master setup
2. Set replica-serve-stale-data=no on all of them
3. Shutdown 1 of the instances 
4. Cannot execute any query against the remaining nodes until the downed master is brought back up

**Comment by JohnSully** [comment]
We've created a new configuration option called replica-quorum that will allow you to specify a quorum.  If at least that many nodes are connected we will allow data to be served even if not all masters are connected.

Fix change: ab4cdd2ed4d3ee9752737d20662178d73d16b4c2
