### ISSUE TITLE
CONTRIBUTING still reference Redis

### ISSUE THREAD

**Issue by hbina** [JohnSully/KeyDB#239]
https://github.com/JohnSully/KeyDB/blob/420ccdfbaebc452b9b374b54c6ebeec4a3ffea36/CONTRIBUTING#L1-L50

I assume the internal have diverged enough at this point to warrant pointing to this repo instead? IDK, could be tagged as a Good First Issue maybe

**Comment by JohnSully** [comment]
I decided to delete the file since I don’t like its tone. KeyDB should have its own at some point but I’d like a community with its own culture to form first.
