### ISSUE TITLE
HGETALL returns NIL, Redis returns EMPTY SET

### ISSUE THREAD

**Issue by wjdavis5** [JohnSully/KeyDB#25]
When you run HGETALL against a key that doesnt exist, KeyDB returns a NIL response. Redis returns (empty list or set). This breaks compatibility with some libraries (StackExchange.Redis)

**SETUP**
```
docker run -it -p 6391:6379 eqalpha/keydb:latest
docker run -it -p 6390:6379 redis:latest
```

**Test**
```
will@45K9VT2:/mnt/c/Users/wdavis$ redis-cli -p 6390 HGETALL test
(empty list or set)
will@45K9VT2:/mnt/c/Users/wdavis$ redis-cli -p 6391 HGETALL test
(nil)
will@45K9VT2:/mnt/c/Users/wdavis$
```

**Comment by JohnSully** [comment]
This is a regression from the REPL3 work.  I've made the fix in 42202c868 which is in the unstable branch.

We're planning a new bug fix release later this week.  Since your on docker I'll update this when the fix lands in our docker image.  In the meantime it will work if you compile from source.

**Comment by wjdavis5** [comment]
Cool, thanks for confirming. I'm seeing something similar with LRANGE but I haven't taken the time to compare and verify. Have you seen any issues with LRANGE that are similar?

**Comment by JohnSully** [comment]
I'm going to need to do a full review which will take some time.  RESP3 standardizes on a nil response, but it should continue to return the same results as before for RESP2 clients (which is currently everything).

**Comment by JohnSully** [comment]
I've done an analysis and fixed a number of additional commands in the change: 740fc6c2b

**Comment by wjdavis5** [comment]
Very nice, thanks for the update, looking forward to getting this running again.
We're testing in qa/uat/staging as a possible stop-gap for rolling out clustering (code base has to change for clustering)

**Comment by JohnSully** [comment]
Docker has been updated with the fixes. 

Note we also have experimental support for multi master and active replication which combined eliminate the need for clustering (and the code changes it causes). This is still experimental though.
