### ISSUE TITLE
CRON docs?

### ISSUE THREAD

**Issue by theoephraim** [JohnSully/KeyDB#253]
I was thinking about how awesome it would be if keydb could run a scheduled script on its own, and then I find mentions of a CRON command, but no docs anywhere. It looks like it is part of the current release version.

Are there any docs available about how to use it?

Thanks!

**Comment by benschermel** [comment]
Hi Theo,

Sorry about the late update on documentation, but here it is:

You can see a blog post about KEYDB.CRON here: https://docs.keydb.dev/blog/2021/01/26/blog-post/ which outlines the feature and goes through some examples.

The 'Commands' section of docs is also now updated: https://docs.keydb.dev/docs/commands/#keydbcron 

-Ben

**Comment by theoephraim** [comment]
Thanks!

CRON is a super useful feature. Luckily I was able to get it running in my use case by reading the code so wasn't blocked by the docs, but hopefully will help others get started.

One thing you might want to add to the docs is how to use it with modjs, as it wasn't totally obvious at first, as keydb is calling lua which calls js...

For example in my loaded modjs scripts, I have an init function which sets up the cron triggers:

```javascript
function MY_CRON_INIT() {
  keydb.call('KEYDB.CRON', 'CRON_TASK_KEY', 'repeat', 1000, "redis.pcall('MY_CRON_TASK')");
}

function MY_CRON_TASK() {...}

keydb.register(MY_CRON_INIT);
keydb.register(MY_CRON_TASK);
```
