### ISSUE TITLE
Unexpected reply to PSYNC from master: -NOAUTH

### ISSUE THREAD

**Issue by ng2dev** [JohnSully/KeyDB#26]
I am trying to add a replica slave from host2:6380 to my master on host1:6379 and added 
masterauth into the appropriate redis-slave.conf.
The master is running with an identical requirepass definition.
However as the slave tries to connect to master it fails with:
 Unexpected reply to PSYNC from master: -NOAUTH Authentication required.

Would someone know what I am doing wrong? Thx

**Comment by JohnSully** [comment]
This is a regression from the multimaster work.  Its fixed if you pull the latest changes, sorry about that.

Fortunately it didn't make it into any of our release builds.

**Comment by ng2dev** [comment]
wow thanks for the quick response!

**Comment by PurpleIsEverything** [comment]
I'm still encountering this issue for both REPLCONF and PSYNC.

``non-fatal: Master doesn't understand REPLCONF uuid```

I'm using the docker containers but I specifically built a new release off commit acdc4fdf to test.

**Comment by JohnSully** [comment]
If you replicate with an older version of KeyDB or Redis this warning is
expected. It’s not an error and replication will work as normal.

I will modify the code to not display this when Active Replica or Master
Master are not enabled.

**Comment by PurpleIsEverything** [comment]
This is the latest commit from the unstable branch, the replication fails with NOAUTH.

**Comment by JohnSully** [comment]
I will investigate then. Sorry for the error.

To confirm the other server is KeyDB with the same version?

**Comment by PurpleIsEverything** [comment]
Yes, it's a local test setup with identical test versions. It seems successful when setup via the CLI the databases are initially synced but nothing syncs after that. When replicaof is setup in the config it just outright fails as above.

**Comment by JohnSully** [comment]
I really need to add more tests with authentication. It’s clear we don’t
have enough coverage here.

These advanced replication features have been  quite disruptive but
hopefully we will get through it soon. Thank you for posting these bugs.

I’ll update this thread when I have a fix.

**Comment by JohnSully** [comment]
Sorry for the delay, this bug occurs when masterauth is below the replicaof setting in the config file (as it is in the template config file).  My prior tests had the order reversed.

It should be fixed in master.  The Docker image will be updated soon.

**Comment by JohnSully** [comment]
Docker has been updated with the fix.

**Comment by PurpleIsEverything** [comment]
Had some free time to test this, seems to be working.

However regardless of how replication is configured it doesn't seem to be working, that's a separate issue though.

**Comment by JohnSully** [comment]
Is there anything notable about your setup?  How many masters?  What commands are you using to test?

Are both multi master and active replication enabled or just one of them?

I was hoping your sync’ing issues were related to authentication.

**Comment by PurpleIsEverything** [comment]
It's a very simple two container setup with a link, it worked before the multi-master update. Tried with both multi-master enabled and disabled.

Using a simple SET and GET test, logs show replication and authentication is fine it looks normal just doesn't seem to sync.

**Comment by JohnSully** [comment]
A colleague and I tried to repro with the following:

Start server A
A> set testkey FOO
Start server B
B> set testkey BAR
A> replicaof B
A> get testkey
    "BAR"
B> set testkey "BAZ"
A> get testkey
   "BAZ"

There must be something we're doing different to you or something unique to your setup.  Would you be able to try that sequence and send me the output of both server A and B as well as output from the monitor command on both servers?

**Comment by PurpleIsEverything** [comment]
After further investigation it looks like it's still an auth issue. Without authentication everything works as expected even with config set replicaof.

With masterauth and requirepass set to the same short alpha numeric password on both keydb instances replication fails.

```
127.0.0.1:6379> MONITOR
OK
1555625495.173550 [0 172.20.0.2:6379] "RREPLAY" "ab7de036-f84f-4d15-ad00-3641021ae96e" "*1\r\n$4\r\nPING\r\n"
1555625495.824241 [0 172.20.0.2:6379] "RREPLAY" "d7955e4a-e672-436f-b20d-641028ae5567" "*1\r\n$4\r\nPING\r\n"
1555625502.680571 [0 172.20.0.2:6379] "RREPLAY" "ab7de036-f84f-4d15-ad00-3641021ae96e" "*3\r\n$3\r\nSET\r\n$7\r\ntestkey\r\n$6\r\nrandom\r\n"
1555625505.216574 [0 172.20.0.2:6379] "RREPLAY" "ab7de036-f84f-4d15-ad00-3641021ae96e" "*1\r\n$4\r\nPING\r\n"
1555625505.867478 [0 172.20.0.2:6379] "RREPLAY" "d7955e4a-e672-436f-b20d-641028ae5567" "*1\r\n$4\r\nPING\r\n"
```

Monitor shows the following it's a very similar log back and forth without authentication setup you see stuff like this in the monitor log immediately following line 3 of the above log: ``1555625352.558634 [0 ?:0] "SET" "testkey" "value"
``

**Comment by JohnSully** [comment]
I've reproduced it - this is docker specific.  The two independent hosts are generating the exact same UUID which results in the host assuming the replication command came from itself.  I've opened issue #28 which tracks this.
