### ISSUE TITLE
No Improvement Switching from Redis to KeyDB

### ISSUE THREAD

**Issue by mina-asham** [JohnSully/KeyDB#265]
This is more of a question really than a bug, but I observed some contentions in my co-hosted Redis instance so I thought I would give KeyDB a try, but the result makes me feel I am maybe missing something so thought I would ask here to clear things up for myself.

My use case is that I have a Redis instance on the same host as my service acting more or less as a local DB, I utilize the Hash data type to store different table (which are huge, in the order of 50 million for example).

Now the latency itself is not that bad on Redis or KeyDB, but I observe the same (or very similar) contention where requests get slightly slower (~10ms) in the higher percentiles (P99).

I have a theory that KeyDB threading is maybe more optimized for the main keyspace and not for the underlying data types  (i.e. if I flatten the data I have and use GET/SET instead of HGET/HSET it might be better?), but I haven't read the code yet to validate that, do you think that this could be the issue here?

Sorry for the lack of numbers/logs/metrics here, I can share a bit more if the above assumption is not correct though.

**Comment by JohnSully** [comment]
Hi @mina-asham HGET/HSET shouldn't appreciably slow down KeyDB and so you should still be seeing improvement.  When specifically looking at P99 latency and sets the more expensive operations could be the determining factor on that.  Are you using any of the more complex set operations like merges?

Also some basic config housekeeping, I assume you have server-threads set to a value >1 and that you have at least as many free cores as server threads (KeyDB works best when it has exclusive use of the core).

**Comment by mina-asham** [comment]
Hi @JohnSully appreciate the prompt reply, I can share a bit more here to answer your questions.
* Mostly I am running hmget (batches around 300, but can be anywhere between 0 and 100) hmset/hmget/hdel with batches up to 5K (I don't use hset/hget at all actually, always multi-key commands, could this be the issue?)
* SLOWLOG shows that it's mostly hmget with 300-800 batches ~3ms for the batch (not disastrous but when it blocks other reads/writes then I guess the effect is more visible)
* I replaced Redis 6.0.0 (4 io threads + io threads do read) with KeyDB 6.0.13 in this test (4 threads + max clients per thread 10 to even out clients, clients seemed distributed based on INFO command)
* I am using a host with Intel Xeon Platinum 8000 having 48 vCPU (24 logical), but I am also running other Redis instances there (run 1 instance per table, ~16 tables, so more CPU than I have on device, but in most cases CPU is around 25% overall so it's not choking there I think), in this test I replaced one of the slower ones (only two are large enough to show this contention) and I saw higher CPU utilization but more or less same latency as when it was running Redis.

I can't share a lot of specific details, but happy to work a bit further on this, let me know if there are any specific configurations you have in mind I can try and tune.

**Comment by JohnSully** [comment]
Hey @mina-asham 

KeyDB open source can only run one command at a time, and so the issue with long commands like large hmgets as it will block other threads for too long.  The open source KeyDB gets its performance by allowing concurrent use of the other parts of the query (parse, and network IO).  KeyDB can do a bit better if you actually run more smaller HMGET commands with fewer keys.

KeyDB Pro is able to be better here with read only queries.  MVCC lets us take snapshots and run read only commands off the snapshot instead of blocking the database and other clients.

**Comment by mina-asham** [comment]
I think that perfectly explains why I am not seeing a huge difference specially that parse/io threading is probably achieving similar performance to Redis 6 in my specific use case, doing smaller hmget through piplelining is something I was itensing to try out in general, happy to test it out on KeyDB too once I make the change to see if there are noticeable differences then.

Feel free to resolve this issue or we can leave it open for me to report back (might take me a week or two to find some free time to try it out again).

Thanks again for the prompt responses and the detailed explanation here :)

**Comment by JohnSully** [comment]
I'll close as there are no direct action items, but please update us with your results here.
