### ISSUE TITLE
Support PMEM

### ISSUE THREAD

**Issue by vongosling** [JohnSully/KeyDB#275]
**Is your feature request related to a problem? Please describe.**
Redis Labs has been working very closely with Intel to ensure that their latest game-changing memory technology— Intel® OptaneTM DC persistent memory—is immediately available to Redis Enterprise users upon its general release with the second-generation Intel® Xeon® Scalable platforms. That Is happening in Last year. Even in its MM mode, the performance is significantly increased. From the know known data, we found the throughput is 2.1 million ops/sec, with a little loss of 8%. The average latency is still less than 1 ms, which is 3% higher[1]. It is believed that this indicator can be further improved under the carefully designed layered architecture. Currently, the Pmem community provides a near-product implementation[2]. We hope KeyDB can be greatly improved in this aspect, help us provide the premium service for those guys with the need of Large Memory, Low Latency, and Low Cost :-)

[1] https://redislabs.com/redis-enterprise/technology/redis-on-flash/
[2] https://github.com/memKeyDB/memKeyDB

**Describe the solution you'd like**
Based on the keydb tiered storage architecture, we could provide warm data detection for better use of PMEM. Or use istorage to integrate the kv implementation of the PMEM community.

**Describe alternatives you've considered**

**Additional context**

**Comment by vongosling** [comment]
ping @JohnSully

**Comment by JohnSully** [comment]
Hey @vongosling

We actually have an internal prototype of KeyDB on PMEM (as well as the hardware in our lab) and are looking at rolling this out next year.  If you want to contact me at: john at eqalpha dot com I would love to talk to you more about it.  I'm not sure I'm ready to talk about this publicly just yet.

Hope you had a great New Years!
-John
