### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [JohnSully/KeyDB#3]
I suggest to reuse a higher level build system than [your current make script](https://github.com/JohnSully/KeyDB/blob/f16d090c728dd23ce23b0d2b316c02d34bf9b0da/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by JohnSully** [comment]
I’m trying to retain compatibility with the upstream Redis code where possible.
