### ISSUE TITLE
Does KeyDB active-active need sentinel?

### ISSUE THREAD

**Issue by plantroon** [JohnSully/KeyDB#30]
Does KeyDB require Redis Sentinel? While I can see how they exist here for being compatible with Redis failover, do I need Sentinel when setting up active-active replication? 

That is, after the master fails, I can continue writing to the replica with just switching the IP address. Do I need to do anything more?

**Comment by JohnSully** [comment]
Active Active replication does not require sentinel. Multi master extends
this feature to more than 2 servers; However this feature still has some
lingering issues with excessive network traffic.

Both features are experimental but Active Replication hasn’t had any major
issues recently.

If you use traditional replication (I.e. don’t enable the two above
features in your config file) then sentinel is still required.

**Comment by plantroon** [comment]
Thanks for the answer.

I picked KeyDB just for this Active-Active feature. Very good to hear that it does not require Sentinel. While I personally do not have a problem with it, many people do. Sentinel is easily replaced with custom scripts for solutions like heartbeat/keepalived, especially useful if these already exist in the server infrastructure.

**Comment by JohnSully** [comment]
Please let me know how it works for you.  I'm available on the gitter chat and of course wIth github issues if you run into problems.

**Comment by mikefaraponov** [comment]
@JohnSully, how can I setup active active with 3 servers and more? Do I need to make a circle of replicaof or I can setup fullnetwork somehow each to each?

**Comment by JohnSully** [comment]
You need to enable multi master with '--multi-master yes' or place that in your config file. Once you do that running multiple replicaof commands (or placing multiple in your config file) will result in additional connections to other masters.   

Please note multi master currently has issues with using large amount of bandwidth.  Its still an experimental feature.

Please see the wiki for more information: https://github.com/JohnSully/KeyDB/wiki/Multimaster-Support
