### ISSUE TITLE
KeyDB compile error (CentOS)

### ISSUE THREAD

**Issue by saga1015** [JohnSully/KeyDB#32]
ENV:
CentOS 6.5 x86_64  with devtoolset-3-gcc (4.9.2)
I use 
make CFLAGS="-march=haswell -m128bit-long-double -m64 "  MALLOC=jemalloc
I get this info:
server.cpp: In function 'char* genRedisInfoString(const char*)':
server.cpp:4453:29: error: expected ')' before 'PRIu64'
         "long_lock_waits:%" PRIu64 "\r\n",
                             ^
server.cpp:4459:36: warning: spurious trailing '%' in format [-Wformat=]
         fastlock_getlongwaitcount());
                                    ^
server.cpp:4459:36: warning: too many arguments for format [-Wformat-extra-args]
make[1]: *** [server.o] Error 1
make[1]: Leaving directory `/opt/opstoolset/source/redis/src/KeyDB-0.9.4-r2/src'

How to fix this ?  very very thanks :-)

**Comment by saga1015** [comment]
I use make CFLAGS="-march=haswell -m128bit-long-double -m64 -D__STDC_FORMAT_MACROS"  MALLOC=jemalloc
compile finished  and keydb-server work fine.

**Comment by JohnSully** [comment]
Thanks for the update.  Your the second bug in the past few days with a CentOS compile issue, I'll be looking at it ASAP.

**Comment by JohnSully** [comment]
__STDC_FORMAT_MACROS is required by the C++ standard, the Ubuntu compiler must be patched to enable it by default.  I've added it to the makefile and verified with CentOS 6 (GCC 7 toolchain)

**Comment by JohnSully** [comment]
Fixed in change 272d9297b
