### ISSUE TITLE
Crash with active replication and multimaster active

### ISSUE THREAD

**Issue by PurpleIsEverything** [JohnSully/KeyDB#34]
I'm running a very basic Docker setup with 2 KeyDB instances, both are configured via their respective config before start and have no previous data.

I've also attempted enabling active replication and multi-master via config and then using replicaof commands on the running instances resulting in the same crash.

https://gist.github.com/PurpleIsEverything/7fb1c90654ad3e07f0b537ec9e4f4331

Thanks.

**Comment by JohnSully** [comment]
I believe this is already fixed with this change: 01eb0a3c7f01d381ffb66c3fec0214d07e8594de

It did not make it into the version you are using.  We will be publishing a new version tomorrow with the cumulative fixes over the last month.

**Comment by PurpleIsEverything** [comment]
Alright! I'll wait for the release and retest. 

Thanks!

**Comment by JohnSully** [comment]
v0.9.5 has been released on docker.  Please reopen if this issue reoccurs.
