### ISSUE TITLE
build error on centos 7

### ISSUE THREAD

**Issue by alochym01** [JohnSully/KeyDB#42]
keydb_v0.9.5, i am getting error with centos 7

cc: error: unrecognized command line option ‘-std=c++14’
make[1]: *** [ae.o] Error 1
make[1]: Leaving directory `/home/hadn/dynomite/KeyDB-0.9.5/src'
make: *** [all] Error 2

[hadn@vsftpd src]$ uname -a
Linux vsftpd 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alochym01** [comment]
1. Install a package with repository for your system:
On RHEL, enable RHSCL repository for your system:
# 1. Install a package with repository for your system:
# On CentOS, install package centos-release-scl available in CentOS repository:
$ sudo yum install centos-release-scl

# On RHEL, enable RHSCL repository for you system:
$ sudo yum-config-manager --enable rhel-server-rhscl-7-rpms

# 2. Install the collection:
$ sudo yum install devtoolset-7

# 3. Start using software collections:
$ scl enable devtoolset-7 bash

for anyone to references

**Comment by JohnSully** [comment]
You got it!  KeyDB targets C++14 so needs newer compilers.  Let me know if you have any other issues.

**Comment by suryasarafe** [comment]
any method for installing without connect to repository.?

I got machine with blocked connection to repository.

**Comment by JohnSully** [comment]
As a Debian person I wasn’t aware of how behind some RHEL/CentOS packages are. We are working on an RPM release however in the meantime perhaps you can build on a less locked down machine (maybe a VM) and move the executable over after its been compiled. 

The alternative is to go with Docker.
