### ISSUE TITLE
Is this RESP protocol-compatible with mainline Redis?

### ISSUE THREAD

**Issue by Qix-** [JohnSully/KeyDB#5]
And if it is, perhaps a note mentioning that in the readme would serve beneficial.

**Comment by JohnSully** [comment]
Yes it is!

I've update the README with the following line:
KeyDB has full compatibility with the Redis protocol, modules, and scripts. This includes full support for transactions, and atomic execution of scripts.

If you experience any compatibility bugs this is considered high priority.  Please open an issue.

**Comment by Qix-** [comment]
Awesome, will definitely be checking this out in the near future. Thanks for the clarification!
