### ISSUE TITLE
Feature Request, Expire members of a set

### ISSUE THREAD

**Issue by imtrobin** [JohnSully/KeyDB#51]
Hi,

One of the much requested features, to expire individual members of a set, is unlikely to get implemented in Redis, hoping KeyDb can take to improve it

https://github.com/antirez/redis/issues/135

**Comment by JohnSully** [comment]
Its good timing since I’m already looking at the expire code heavily. 

What do you think of triggering a lua script on expire?  That way custom behavior can be added for any type as needed. 

The one hesitation I have is if you have this ability for sets - then what about the other set-like data types?

**Comment by imtrobin** [comment]
I would foresee other types like hashes too. I'm not a great fan of calling another script. My use case is quite simple, without expire on individual keys in a set, I'm forced to put them in global space, and there will be collisions.

Perhaps I would think it's an extenion method, like EXPIREMEMBER

**Comment by JohnSully** [comment]
The trouble is that internally the values are not strongly typed. So often KeyDB/Redis doesn’t know if its a set/ziplist/etc. You can even craft values that are valid as multiple types. 

It would have to be EXPIREMEMBER [type] [key] [subkey]. 

It is definitely doable though.

**Comment by JohnSully** [comment]
A prototype of EXPIREMEMBER is now in the subexpire branch: https://github.com/JohnSully/KeyDB/tree/subexpire

The command is: EXPIREMEMBER [key] [subkey] [seconds]

This is still a prototype so please don't try this in production - but I think this feature will work very well.  I'd love to hear any suggestions you have for improving this command.   Right now only sets are supported but this is a temporary limitation.

I will continue to update this issue as the feature makes it way to our stable release.

**Comment by imtrobin** [comment]
Looks good, thanks!

**Comment by JohnSully** [comment]
This has been merged into the unstable branch in prep for its v5.1 release.  The unstable docker updates at 4am EST each night if you would like to try it via docker.

**Comment by vfrz** [comment]
Hello @JohnSully ,
I am very happy to have found this fork which support member expiration. I've tested it and it works very well.
However there is a feature I'd like to see: have the possibility to know/get the deleted value on the "notify-keyspace-events" notification system. Currently, we can only get the key of the set by parsing the channel.
To be honest, I've just started digging into Redis/KeyDB and I don't know much about it, so I don't even know if it's possible to add this feature without rewriting the whole project.

So, do you think that's possible? And if yes, would you agree to implement it? (Or maybe it's already possible?)

Thanks in advance.

**Comment by JohnSully** [comment]
Thanks @vfrz this is an oversite.  I'll add a new subexpire keyspace event so you can track them.

**Comment by JohnSully** [comment]
@vfrz I moved your feature request to a new issue #85.  Because I'm hoping to release v5.1 on Monday there won't be time to do it as part of that release.
