### ISSUE TITLE
Does KeyDB support WAIT command in active-active to wait for data propagation?

### ISSUE THREAD

**Issue by mikefaraponov** [JohnSully/KeyDB#52]
x.y.z.d:6379> wait 1 1
(error) ERR WAIT cannot be used with replica instances. Please also note that since Redis 4.0 if a replica is configured to be writable (which is not the default) writes to replicas are just local and are not propagated.

**Comment by mikefaraponov** [comment]
This feature is vital for me

**Comment by mikefaraponov** [comment]
probably it relates to https://github.com/JohnSully/KeyDB/issues/45

**Comment by JohnSully** [comment]
This looks like just an oversight - the feature should work.  Let me test it and unblock it.

**Comment by JohnSully** [comment]
Upon testing this fix I found a scenario where the replica is undercounting the backlog. Outside of this command it may result in extra full syncs however with this command it will wait forever. 

Once that issue is resolved I can enable this for Active Replication.

**Comment by JohnSully** [comment]
This is now fixed in the unstable branch.

Change:
a5784ef09e71a9a45780a8f3dbab875b1f1fe1a5

**Comment by JohnSully** [comment]
I’ve done quite a bit of testing as well as adding new tests to track this. 
This will be our v5 release slated for Monday.

**Comment by JohnSully** [comment]
This command is enabled in v0.9.6. Docker is updated with this new version.
