### ISSUE TITLE
KeyDB reports very low redis_version

### ISSUE THREAD

**Issue by azazeal** [JohnSully/KeyDB#53]
Hello!

First I'd like to thank you for all your hard work. I've noticed that via the `INFO` command, KeyDB is reporting a very low `redis_version`. This unfortunately breaks every piece of software which tests against this value.

Is it possible that instead of yielding the version of KeyDB in that field, it'd be better for compatibility purposes, to yield a version of Redis that the build is compatible with and maintain version information for KeyDB in a separate key like `keydb_version`?

**Comment by JohnSully** [comment]
Hi,

KeyDB’s next major version will be 5.0 (instead of 1.0) in order to solve
these problems.

In the mean time we have the version-override configuration option to set
the required version if necessary.

**Comment by azazeal** [comment]
Thanks for the tip!
