### ISSUE TITLE
Starting one client causes another to crash with latest build

### ISSUE THREAD

**Issue by PurpleIsEverything** [JohnSully/KeyDB#58]
https://gist.github.com/PurpleIsEverything/c22b4bb4242c887d5d796dce8500e55e

**Comment by JohnSully** [comment]
This crash occurred during replication synchronization.  Can you give me an idea of your replication setup?  Are you using Active Replication?  How many masters/replicas?

**Comment by PurpleIsEverything** [comment]
Active replication yes, we also have/had multi-master on, though the option seems to be gone from the config. 4 instances all with the same configuration essentially connecting to each other.

**Comment by JohnSully** [comment]
multi-master was updated to "yes/no"  You can enable with 'multi-master yes' in your config file.

**Comment by PurpleIsEverything** [comment]
Yes we have it enabled along with active replication, each node is configured with replicaof of the others via the command line (all dockerized)

**Comment by JohnSully** [comment]
Fixed in c8516f3dc484920de4fc52acd72f5104d643ca87

This was a regression from the fix for issue #54, sorry for the trouble it has caused.  I will rebuild docker shortly.
