### ISSUE TITLE
zrangebyscore can return nil when zset is a skiplist

### ISSUE THREAD

**Issue by bpo** [JohnSully/KeyDB#61]
This looks like the same problem seen in #38, but with skiplists instead of ziplists.

```
# build a largish sorted set that will be skiplist encoded
$ redis-cli zadd foo 5 `seq 0 1000`
(integer) 501
$ redis-cli debug object foo
Value at:0x7f830fa5ee48 refcount:1 encoding:skiplist serializedlength:5449 lru:3126995 lru_seconds_idle:8
$ redis-cli zrangebyscore foo -inf -1
(nil)
```

**Comment by JohnSully** [comment]
This is a regression from upstream Redis RESP3 work.  I had done a code analysis for these but must have missed this one.  It is fixed in change: 4e30a5b4e

I've also forwarded this bug to Redis where it also repros: https://github.com/antirez/redis/issues/6250
