### ISSUE TITLE
0.9.6 version, keydb-cli and libcurl error

### ISSUE THREAD

**Issue by oruchreis** [JohnSully/KeyDB#62]
I'm using keydb in a kubernetes environment. I've updated image version from 0.9.5 to 0.9.6, but my keydb-cli scripts has failed with this error:
`keydb-cli: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory`
My script has simple redis commands like `SHUTDOWN SAVE` or `REPLICAOF someone`, etc..

**Comment by benschermel** [comment]
Thanks, the docker containers have been updated to include libcurl4-openssl-dev. This should work now. Security updates have also been pushed. Dockerfiles will be updated in docs.keydb.dev tonight.

**Comment by benschermel** [comment]
dockerfiles can be seen here: https://docs.keydb.dev/docs/dockerfiles/
closing issue.
