### ISSUE TITLE
keydb in ubuntu repos

### ISSUE THREAD

**Issue by tuwid** [JohnSully/KeyDB#72]
Hi, are there any plans to have keydb available via apt-get or via some special repos prebuilt?

**Comment by JohnSully** [comment]
Hi tuwid,

It should be straightforward to setup a PPA. I’ll look into it.

**Comment by benschermel** [comment]
We now have a PPA with builds for bionic arm64, amd64, i386. https://launchpad.net/~eqalpha/+archive/ubuntu/keydb-server. Disco and Xenial builds will likely be added in the near future. Documentation on docs.keydb.dev to be updated soon.

Installation can be done with the following commands:
```
sudo add-apt-repository ppa:eqalpha/keydb-server
sudo apt-get update
sudo apt install keydb-server
```
This installs binaries and systemd files for keydb-server to run as a service. If you want to install and run sentinel as a service then `sudo apt install keydb-sentinel`. 

To start/stop service:
```
service keydb-server start
service keydb-server stop
```
keydb.conf configuration file located in /etc/keydb/keydb.conf
Logfile at  /var/log/keydb/keydb-server.log
directory for .rdb located at /var/lib/keydb/dump.rdb

If there are any issues let me know.

**Comment by JohnSully** [comment]
Please reopen if you experience any issues.

**Comment by simplexx** [comment]
Very nice, thank you!
Call me old school, but I think this should be added to the official install manual, better than compiling from the source and certainly better than docker, which imo is just used because of the hype in most cases.

**Comment by steamboatid** [comment]
Error: could not find a distribution template for Raspbian/buster

**Comment by negrusti** [comment]
@benschermel - /var/run/keydb/ is not getting created for me:
keydb-server.service: Can't open PID file /var/run/keydb/keydb-server.pid (yet?) after start: No such file or directory

**Comment by benschermel** [comment]
Hi Grigory, 

 

This is working fine for me (just tested again) on Ubuntu 18.04. Files are being created. What OS are you running on? Currently bionic build is supported (amd64 & arm64). Was this previously working or first time installing? I assume you followed these steps:

```

sudo add-apt-repository ppa:eqalpha/keydb-server

sudo apt-get update

sudo apt install keydb-server

```

You can uninstall with `apt autoremove --purge keydb-server`

**Comment by teotikalki** [comment]
I'm interested in a Debian rather than Ubuntu repository (or just apt package) (and it seems like @steamboatid is as well). Should a separate issue be opened for this?

**Comment by negrusti** [comment]
Installing keydb-tools breaks npm for me:
```
apt-get install keydb-tools
The following additional packages will be installed:
  libcurl4-openssl-dev
The following packages will be REMOVED:
  libssl1.0-dev node-gyp nodejs-dev npm
The following NEW packages will be installed:
  keydb-tools libcurl4-openssl-dev
```

**Comment by benschermel** [comment]
Hi Grigory,

 

I believe this should now be fixed in our latest PPA which is now hosted by keydb, not launchpad. We offer multiple architectures and have packages available for both keydb and keydb pro.

 

$ curl -s --compressed "https://download.keydb.dev/keydb-ppa/KEY.gpg" | sudo apt-key add -

$ sudo curl -s --compressed -o /etc/apt/sources.list.d/keydb.list https://download.keydb.dev/keydb-ppa/keydb.list

$ sudo apt update

$ sudo apt install keydb

 

Further instructions to install and use are here: https://docs.keydb.dev/docs/ppa-deb/.

 

Let me know if you have any issues

 

Ben

**Comment by nurettin** [comment]
On ubuntu when I add the repository (either keydb.dev or the ppa) I get a timeout when the installation process tries to start keydb-server. It checks whether the pid file is created and then times out. Version 5:5.3.0-1chl1~bionic1
