### ISSUE TITLE
Segmentation fault in current version from 10th Aug

### ISSUE THREAD

**Issue by dufrygrant** [JohnSully/KeyDB#74]
dump.rdb got to about 400Mb of production site Magento 2.2 traffic, then core-dumped & refused to restart (would not read the dump file).

Have since disabled save to RDB and am attempting usage again...

Bug report follows:
2601:C 10 Aug 2019 20:54:51.020 * Notice: "active-replica yes" implies "replica-read-only no"
2601:C 10 Aug 2019 20:54:51.020 # oO0OoO0OoO0Oo KeyDB is starting oO0OoO0OoO0Oo
2601:C 10 Aug 2019 20:54:51.020 # KeyDB version=0.0.0, bits=64, commit=4e9bfcf8, modified=0, pid=2601, just started
2601:C 10 Aug 2019 20:54:51.020 # Configuration loaded
2610:M 10 Aug 2019 20:54:51.022 * Increased maximum number of open files to 10032 (it was originally set to 1024).

                                        KeyDB 0.0.0 (4e9bfcf8/0) 64 bit

                                        Running in standalone mode
                                        Port: 6379
                                        PID: 2610

                     Like KeyDB? Star us on GitHub!

                     https://github.com/JohnSully/KeyDB

2610:M 10 Aug 2019 20:54:51.023 # Server initialized
2610:M 10 Aug 2019 20:54:51.023 * Loading RDB produced by version 0.0.0
2610:M 10 Aug 2019 20:54:51.023 * RDB age 2363 seconds
2610:M 10 Aug 2019 20:54:51.023 * RDB memory usage when created 456.54 Mb

=== KEYDB BUG REPORT START: Cut & paste starting from here ===
2610:M 10 Aug 2019 20:54:51.030 # ------------------------------------------------
2610:M 10 Aug 2019 20:54:51.030 # !!! Software Failure. Press left mouse button to continue
2610:M 10 Aug 2019 20:54:51.030 # Guru Meditation: decrRefCount against refcount <= 0 #object.cpp:376
2610:M 10 Aug 2019 20:54:51.030 # (forcing SIGSEGV in order to print the stack trace)
2610:M 10 Aug 2019 20:54:51.030 # ------------------------------------------------
2610:M 10 Aug 2019 20:54:51.030 # KeyDB 0.0.0 crashed by signal: 11
2610:M 10 Aug 2019 20:54:51.030 # Crashed running the instruction at: 0x56308c5a8cdc
2610:M 10 Aug 2019 20:54:51.030 # Accessing address: 0xffffffffffffffff
2610:M 10 Aug 2019 20:54:51.030 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/usr/local/bin/keydb-server *:6379(_serverPanic+0x14c) [0x56308c5a8cdc]

Backtrace:
/usr/local/bin/keydb-server *:6379(logStackTrace(ucontext_t*)+0x6b) [0x56308c5a9e1b]
/usr/local/bin/keydb-server *:6379(sigsegvHandler(int, siginfo_t*, void*)+0xbf) [0x56308c5aa5af]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f64a89db890]
/usr/local/bin/keydb-server *:6379(_serverPanic+0x14c) [0x56308c5a8cdc]
/usr/local/bin/keydb-server *:6379(decrRefCount(robj_roptr)+0x12e) [0x56308c56cc8e]
/usr/local/bin/keydb-server *:6379(rdbLoadRio(_rio*, rdbSaveInfo*, int)+0x262) [0x56308c5870a2]
/usr/local/bin/keydb-server *:6379(rdbLoadFile(char*, rdbSaveInfo*)+0x52) [0x56308c587ae2]
/usr/local/bin/keydb-server *:6379(rdbLoad(rdbSaveInfo*)+0x1f) [0x56308c587b4f]
/usr/local/bin/keydb-server *:6379(loadDataFromDisk()+0x9e) [0x56308c5591ae]
/usr/local/bin/keydb-server *:6379(main+0x7d1) [0x56308c549fc1]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f64a85f9b97]
/usr/local/bin/keydb-server *:6379(_start+0x2a) [0x56308c54a74a]

------ INFO OUTPUT ------
# Server
redis_version:0.0.0
redis_git_sha1:4e9bfcf8
redis_git_dirty:0
redis_build_id:a70f897562a19bfc
redis_mode:standalone
os:Linux 4.15.0-1044-aws x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.4.0
process_id:2610
run_id:4f877e21de8eb6b59646fa7b2322e9562f6e10fd
tcp_port:6379
uptime_in_seconds:0
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:5189403
executable:/usr/local/bin/keydb-server
config_file:/etc/redis/6379.conf

# Clients
connected_clients:0
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0
thread_0_clients:0
thread_1_clients:0
thread_2_clients:0
thread_3_clients:0

# Memory
used_memory:11302792
used_memory_human:10.78M
used_memory_rss:0
used_memory_rss_human:0B
used_memory_peak:11302792
used_memory_peak_human:10.78M
used_memory_peak_perc:inf%
used_memory_overhead:9397984
used_memory_startup:9125080
used_memory_dataset:1904808
used_memory_dataset_perc:87.47%
allocator_allocated:0
allocator_active:0
allocator_resident:0
total_system_memory:10641981440
total_system_memory_human:9.91G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:8192000000
maxmemory_human:7.63G
maxmemory_policy:allkeys-lru
allocator_frag_ratio:-nan
allocator_frag_bytes:0
allocator_rss_ratio:-nan
allocator_rss_bytes:0
rss_overhead_ratio:-nan
rss_overhead_bytes:0
mem_fragmentation_ratio:-nan
mem_fragmentation_bytes:0
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:1
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1565470491
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
loading_start_time:1565470491
loading_total_bytes:398640215
loading_loaded_bytes:0
loading_loaded_perc:0.00
loading_eta_seconds:1

# Stats
total_connections_received:0
total_commands_processed:0
instantaneous_ops_per_sec:0
total_net_input_bytes:0
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:73a6629ccc8ea7df64be53776f438a622a6933e6
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.004924
used_cpu_user:0.004924
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
server_threads:4
long_lock_waits:0

# Commandstats

# Cluster
cluster_enabled:0

# Keyspace
db6:keys=162,expires=29,avg_ttl=21447388

------ CLIENT LIST OUTPUT ------

------ REGISTERS ------
2610:M 10 Aug 2019 20:54:51.031 #
RAX:0000000000000000 RBX:00007ffdd1849bc0
RCX:0000000000000001 RDX:000056308deea010
RDI:0000000000000000 RSI:000056308deea118
RBP:000056308c6971fb RSP:00007ffdd1849ba0
R8 :00007f64a9d52000 R9 :00007f64a9d52000
R10:00000000ffffffd0 R11:0000000000000206
R12:0000000000000178 R13:0000016c82485a86
R14:0000000000000004 R15:00007ffdd184a280
RIP:000056308c5a8cdc EFL:0000000000010206
CSGSFS:002b000000000033
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849baf) -> 4e26dc9990bb1700
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849bae) -> 0000000000000018
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849bad) -> 00007f64a8031849
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849bac) -> 0000000000000000
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849bab) -> 4e26dc9990bb1700
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849baa) -> 01007f64a8031849
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba9) -> 00007ffdd1849c20
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba8) -> 0000000000003020
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba7) -> 3d3c20746e756f63
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba6) -> 6665722074736e69
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba5) -> 61676120746e756f
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba4) -> 4366655272636564
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba3) -> 00007ffdd1849cd0
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba2) -> 00007ffdd1849da0
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba1) -> 0000003000000018
2610:M 10 Aug 2019 20:54:51.031 # (00007ffdd1849ba0) -> 0000000000000002

------ FAST MEMORY TEST ------
2610:M 10 Aug 2019 20:54:51.031 # Bio thread for job type #0 terminated
2610:M 10 Aug 2019 20:54:51.031 # Bio thread for job type #1 terminated
2610:M 10 Aug 2019 20:54:51.031 # Bio thread for job type #2 terminated
*** Preparing to test memory region 56308c8f2000 (2256896 bytes)
*** Preparing to test memory region 56308deea000 (135168 bytes)
*** Preparing to test memory region 56308df0b000 (131072 bytes)
*** Preparing to test memory region 7f64a56fd000 (4194304 bytes)
*** Preparing to test memory region 7f64a5afe000 (8388608 bytes)
*** Preparing to test memory region 7f64a62ff000 (8388608 bytes)
*** Preparing to test memory region 7f64a6b00000 (8388608 bytes)
*** Preparing to test memory region 7f64a7300000 (17825792 bytes)
*** Preparing to test memory region 7f64a89c5000 (16384 bytes)
*** Preparing to test memory region 7f64a8be4000 (16384 bytes)
*** Preparing to test memory region 7f64a9523000 (16384 bytes)
*** Preparing to test memory region 7f64a9d4e000 (49152 bytes)
*** Preparing to test memory region 7f64a9d63000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: _serverPanic (base: 0x56308c5a8b90)
Module: /usr/local/bin/keydb-server *:6379 (base 0x56308c50e000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x56308c5a8b90 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
2610:M 10 Aug 2019 20:54:51.154 # dump of function (hexdump of 460 bytes):
4154554189f4534889fd4881ece001000084c048898c24480100004c898424500100004c898c245801000074400f298424600100000f298c24700100000f299424800100000f299c24900100000f29a424a00100000f29ac24b00100000f29b424c00100000f29bc24d001000064488b042528000000488984242801000031c0488d842400020000488d5c24204c8d4c24084989d0b900010000ba010000004889442410488d842430010000be000100004889dfc744240818000000c744240c300000004889442418e872fff9ff488b056b3734008b802c24000085c07505e86cf7ffff488d3545680f0031c0bf03000000e8f999faff488d356a680f0031c0bf03000000e8e699faff488d35577a0f004589e04889e94889da31c0bf03000000e8ca99faff488d357b680f0031c0bf03000000e8b799faff488d35f0670f0031c0bf03000000e8a499faffc60425ffffffff78488b842428010000644833042528000000750c4881c4e00100005b5d415cc3e83801faff0f1f8400000000004157415649c7c6ffffffff415541544989f455534889d34889fdba040000004889df4881ecd80300004989cd64488b04252800000048898424c803000031c00fb601488d74243483e00f0fc8

=== KEYDB BUG REPORT END. Make sure to include from START to END. ===

**Comment by JohnSully** [comment]
@dufrygrant I'm having trouble finding which version you are currently running. 0.0.0 indicates it is from the unstable branch however the commit hash doesn't match up.  Are there local modifications applied?

If you are willing to share the rdb file privately that would be immensely helpful (email me: john at eqalpha dot com).  Otherwise can you try with an unmodified build of RELEASE_5?

**Comment by dufrygrant** [comment]
Hi John,

It was just from ‘git clone [url]’ as of Saturday 10th Aug.  No specific version number.

Also, the RDB file’s gone, unfortunately.

If it’s desirable for it to be replicated (either with the version as described or the RELEASE_5 version), I can attempt it, but might take some time to attach it to a non-production platform with sufficient traffic to reproduce.

Grant

**Comment by JohnSully** [comment]
There are some changes to RDB load/save unique to the unstable branch. If you repro this issue again it would be good if you can see if it repros in RELEASE_5 too. In the meantime I will try to find it with fuzzing. 

One other question, are you using subkey expires?

**Comment by dufrygrant** [comment]
No, we’re not.

**Comment by JohnSully** [comment]
This is fixed in change: 070c48187

It only affects the unstable branch.  Thanks for reporting this!
