### ISSUE TITLE
ZFS support?

### ISSUE THREAD

**Issue by rickytato** [JohnSully/KeyDB#78]
I've this problem:

`6844:C 03 Sep 2019 23:32:29.874 # Scratch file system does not support Copy on Write.  To fix this scratch-file-path must point to a path on a filesystem which supports copy on write, such as btrfs.`

LXC container on Proxmox server and ZFS local storage on SSD.

**Comment by JohnSully** [comment]
Hi @rickytato,

The FLASH feature requires a filesystem with FICLONE support.  We use feature detection to determine if a file system is compatible (we don't explicitly whitelist).  Unfortunately ZFS does not support FICLONE and cannot be used.  We recommend BTRFS.
