### ISSUE TITLE
BITOPRANGE command

### ISSUE THREAD

**Issue by JohnSully** [JohnSully/KeyDB#79]
Forwarded from Redis issue: https://github.com/antirez/redis/issues/6356 initially requested by @Qix- 

This tracks implementation of the BITOPRANGE command.  It allows you to choose subsets of source keys upon which the normal bitop command applies.  The syntax is:

BITOPRANGE OPERATION dstkey srckey start:end [srckey start:end ...]
end may be -1 to signify the full length of the key.

A prototype is implemented in the bitoprange branch.

**Comment by Qix-** [comment]
Sorry for the delay - I've been on vacation!

The only thing that feels like it's missing is where to place the result in the destination key.

**Comment by JohnSully** [comment]
I think what I might do instead is implement the shift operators in bitop. If you need the result elsewhere you can do it with a shift.

**Comment by Qix-** [comment]
Yeah, absolutely - those are definitely missing and would solve the other problem as well. :+1:

**Comment by JohnSully** [comment]
I think what I will do is implement the shift and rotate operators instead of this command. 

BITOPRANGE will likely run much faster though so if you still have performance problems I can still implement that command.

**Comment by Qix-** [comment]
Sounds like a good plan!

For our use-case, when it comes time to optimize we'll most likely move the algorithm to a redis C module, though I appreciate the concern ^^

**Comment by JohnSully** [comment]
I implemented both the LSHIFT and RSHIFT operators.  These will be included in the v5.1 release.  Change ba365298ed37a76f0a8630e0ec6c86393293aebe

Note that the shifts are done little endian to match X86 processors.  This can be confusing when looking at the results in the CLI.
