### ISSUE TITLE
How to configure a cluster with several KeyDBs ?

### ISSUE THREAD

**Issue by Caldas** [JohnSully/KeyDB#8]
I can't find documentation about use KeyDB as a cluster

**Comment by JohnSully** [comment]
Hi Caldas,

The process should be the same as Redis including supporting the same tools and workflow.  We worked hard to maintain full compatibility with Redis - but your right we do need our own documentation.  I'll get that up as soon as I can.

**Comment by JohnSully** [comment]
A little progress on this, we've added Active Replication support and have documented that here:
https://github.com/JohnSully/KeyDB/wiki/KeyDB-(Redis-Fork):-Active-Replica-Support

**Comment by Caldas** [comment]
Very nice @JohnSully 👍

**Comment by JohnSully** [comment]
Our docs website is up with Active Replication and traditional clustering: https://docs.keydb.dev/docs/active-rep
