### ISSUE TITLE
Status of multithreading for cpu-heavy commands

### ISSUE THREAD

**Issue by ddorian** [JohnSully/KeyDB#84]
Hi,

I'm guessing this still doesn't work for cpu-intensive commands (to be distributed at the same time on different threads) ? 

Even only "read" operations ? Maybe that comes with read/write lock ?

Regards

**Comment by JohnSully** [comment]
Hi @ddorian

We’re made progress on this front. You can now execute commands against other database numbers while a KEYS command is executing (note: not yet in the release branch). 

Is there any specific long running command you had in mind?

**Comment by ddorian** [comment]
In my case I mean executing concurrent commands on `same-data`. 

Suppose you have a command that is `cpu & ram intensive`. Increasing replication wastes ram. Splitting the command into multiple keys and aggregating... you get normal-redis again.

Say, a hot key, but the command isn't just `get` but say, search. So you want all threads to be able to work with the same data at the same time.

This is explained https://oss.redislabs.com/redisearch/Threading.html in single-thread.
While it can be somehow in multi-thread (think elasticsearch, where each core can do a search on the same data at the same time).

Same time in this case is only for reading and not insert/update/delete.

**Comment by JohnSully** [comment]
This is the direction we’re moving in. However I think you might be surprised how much the current implementation helps with this scenario. Even for complicated commands network IO and parsing are usually far more expensive than the actual command. These are all fully parallelized in KeyDB today.

**Comment by JohnSully** [comment]
Please reopen if I haven't answered your question fully.  I will update this if the situation changes.
