### ISSUE TITLE
Write scaling on multiple cores

### ISSUE THREAD

**Issue by ddorian** [JohnSully/KeyDB#91]
I read somewhere from you:
Scaling reads, the idea is to be able to read from the hash-table from multiple threads and still only write on 1 thread.

What about scaling writes:

0. Create a hash-table for each core based on {slot} (like choosing server). 
1. After doing the hash-read-lock, all threads can read in all hash-tables (hot keys reading)
2. Each thread can only write on own hash-table (redis compatibility)
3. Each thread can parse-request, move network (helping write scaling on hot keys)

Makes sense ?

**Comment by JohnSully** [comment]
Your understanding of KeyDB's multi-threading is not quite correct.  Any thread is able to write to the hash table.  Instead clients are bound to threads and load balanced across them.  Access to the internal hash table is protected via a lock.  In the future we hope to implement MVCC so concurrent access is possible, however even with the lock access is extremely fast.

**Comment by ddorian** [comment]
>  Any thread is able to write to the hash table.
Not at the same time. Yes mvcc will do. But splitting into a hash-table-per-core will be non-blocking write on each of them. And it will work with redis-cluster. This follows scylladb's design.

Access is fast, but doing cpu-heavy writes is still same speed.

**Comment by JohnSully** [comment]
My main concern here is that memory efficiency tends to be even more important to most users than CPU speed.  Having multiple hash tables would be problematic in that regard.  I am interested in cases that are CPU bound, if KeyDBs multi-threading is not sufficient I'd love to learn more about the use case.

**Comment by ddorian** [comment]
> memory efficiency tends to be even more important
You can have something that satisfies both worlds by doing a `1 hash table for x cores`. 

A simple example is a search engine. Heavy-cpu writes to create/merge inverted-index and heavy-reads cause of complex queries.

**Comment by JohnSully** [comment]
This is a good idea and certainly would improve scalability.  Right now we're primarily limited by TCP packet throughput not lock contention on the database so this is not something I plan to look at right now.  If lock contention becomes the bottleneck I will revisit this.
