### ISSUE TITLE
Clarify Implications of Flash Storage

### ISSUE THREAD

**Issue by turbo** [JohnSully/KeyDB#92]
Hi,

I find the page on flash storage (https://github.com/JohnSully/KeyDB/wiki/FLASH-Storage) a bit confusing. Does the usage of this option imply that one could use data sets larger than memory, with KeyDB paging between disk and RAM to optimize access?

If not, could you please outline one or two concrete usage scenarios for this mode?

Thanks!

**Comment by JohnSully** [comment]
Yes it means exactly that: You can use datasets larger than your RAM and it will page between the two (using the OS paging strategy).

**Comment by turbo** [comment]
Thanks for clarifying. Did you find that using the OS strategy is sufficient or is there a plan to implement a custom usage-based one?

**Comment by JohnSully** [comment]
It works OK but now quite as good as I would like. The advanced_db branch has work to improve it. I don’t have a timeline on when that will be ready just yet.
