### ISSUE TITLE
KeyDB unresponsive

### ISSUE THREAD

**Issue by windvlaag** [JohnSully/KeyDB#96]
We have the database running on 3 server-threads in our production environment.
It is set up to be used a cache only.

The server is running on ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-164-generic x86_64)
We are using the 5.1.0 build

It had been running for 6 days straight after installation.
KeyDB was using approx 1200 MB of memory according to the last logged 'info memory' command.

We had a bump in traffic for the application/website we use it as a cache for (around 2000 users simultaneously). 
Around this time we notice a large amount of errors in our application log about timeouts (we have configured a 5000ms command timeout) on _GET_ and _UNLINK_ commands.

A short time after the process does not respond to connections any more.
Now (about 20 hours later) I've tried to restart the service, which did not have any effect.
I've had to forcefully kill the process using _SIGKILL_ (it didn't seem to respond to _SIGINT_).

The log file is completely empty except for the _SIGINT_, as such i'm clueless as to what might have caused keyDB to become unresponsive.

I've attached the config we're using in the hope there might be some mistake in our configuration.
[keydb config.txt](https://github.com/JohnSully/KeyDB/files/3749791/keydb.config.txt)

**Comment by JohnSully** [comment]
It sounds like a deadlock. I haven’t seen one of those in a while. Can you give me an idea of what sort of queries your using? Pub/Sub?  Active Replication? Clustering?

That information should give me a few places to start looking.

**Comment by JohnSully** [comment]
Change fa797408d doesn't quite fix the problem but does implement deadlock detection.

**Comment by windvlaag** [comment]
Currently the only queries we run are: 'GET' 'SET', 'UNLINK','INFO'.
Almost all of the 'SET' do have a TTL attached, usually items are kept in there up to an hour.
The database usually contains around 140.000 items.
The largest amount of these contain small of html, around 16kb each.

The largest values are 200-500kb, but there are only around 800 of these in total.

We do have keyspace events configured 'Ex' but besides them being triggerd we are currently not using these.

**Comment by JohnSully** [comment]
With the new tooling I was able to identify a few potential issues.  Most occur around clients being disconnected.  Fixes are in changes:
4986dc6da9855ba14d760a89f13ec40c8bea4baf
1a70af2ae13962db038b0635cc29488019323538
5a8cb77d0df7f319809ff965a72fe46925f49289

**Comment by vvhungy** [comment]
One simple way to test for keydb response is to run "keydb-cli MONITOR" from a remote machine.
I got one of my keydb server (~50k rps) become un-responsive by testing this way.

**Comment by JohnSully** [comment]
Release 5.1.1 is now out with fixes for these and a few other issues I've found. @vvhungy your monitor deadlock should be fixed as well.  A new docker release is being built which may take a few hours.

**Comment by vvhungy** [comment]
@JohnSully: pls check the latest 5.1.1 release. It seems that you uploaded same 5.1.0 source-code.

**Comment by JohnSully** [comment]
@vvhungy You're right.  The label has been updated.  (Docker is still building).
